.pre-commit-config.yaml
.vscode/launch.json
Makefile
configs/etl/reference.yaml
poetry.lock
src/etl/intervals/andersson2014.py
src/etl/intervals/helpers.py
src/etl/intervals/javierre2016.py
src/etl/intervals/jung2019.py
src/etl/intervals/thurman2012.py
src/run_intervals.py

Intervals calculated from the platform target
The intention now is to use Platform target for gene index as-is.
The changes in this PR aim to maintain all functionality from intervals.
Coverage should increase, due to mappings to obsoleted gene symbols.
Counts not yet compared to the main branch.

Intervals from target

---

.pre-commit-config.yaml
.vscode/settings.json
src/etl/common/ETLSession.py
src/etl/json/__init__.py
src/etl/json/schemas/intervals.json
src/etl/json/schemas/targets.json
tests/test_schemas.py

1. New `json/schemas` directory stores relevant Spark DataFrame schemas 
2. `read_parquet` in `ETLSession` allows providing schema from the directory when reading a DataFrame
3. `validate_df_schema` validates a DataFrame complies with a given schema from the directory
4. pytest ensures all schemas in the directory are valid Spark schemas

Support to ensure schemas

---

configs/etl/reference.yaml
src/etl/common/utils.py
src/etl/variants/variant_annotation.py
src/etl/variants/variant_index.py
src/run_variant_annotation.py
src/run_variant_index.py

These are optimisation improvements to both the variant index and annotation.
**Variant index**:
- Improved plan. We avoid one shuffling step in the credible set by partitioning the dataset on the chromosome and then providing the partitioning key also in step where I drop the duplicates.
- [Job](https://console.cloud.google.com/dataproc/jobs/e8c01368a0444dc3a068447b3887cf26?region=europe-west1&project=open-targets-genetics-dev): 6'. Very small improvement in comp time (~40sec) 
**Variant annotation**
- Improved output. Dataset is now partitioned by chromosome and ordered by position without a big detriment in the comp time.
- [Job](https://console.cloud.google.com/dataproc/jobs/12bd4aa3c9f64c43850211e58971d7e6/configuration?region=europe-west1&project=open-targets-genetics-dev): 2h40'

Minor improvements to the variant datasets generation

---

src/conftest.py
src/otg/dataset/study_locus.py
src/otg/method/ld.py
tests/conftest.py

Testing sessions are now configured to run as single-threaded operations and other optimisations to minimise the cost of initialising the spark session. This change also ensures that data frames are not shuffled making it easier to test the expected outputs. (This was otherwise failing when changing python/spark functions)

Test session streamline

---

.vscode/settings.json
src/otg/common/schemas.py
src/otg/dataset/study_locus.py
src/otg/method/pics.py
tests/dataset/test_study_locus.py
tests/method/test_pics.py

This PR is coauthored with @d0choa, and addresses the main piece of logic that defines which is the credible set in a region.
It is a significant change in terms of logic and style. To define a credible set, we sort the variants in a locus by their posterior probability, informing about the most likely variants to be explaining that signal. For the definition of which variants are part of the 95% credible set, the cumulative sum of the probabilities (already sorted) is calculated, so that we pick which all variants that explain 95% of the association.
We realised that the current logic was not doing this, as for the calculation of the cumulative sum, we were iterating on each tagging variant within `credibleSet`, and aggregating over the `posteriorProbability`, i.e. the cumulative sum was …

Redefinition of credible set annotation

---

config/datasets/gcp.yaml
pyproject.toml
src/otg/common/spark_helpers.py
src/otg/dataset/study_index.py
src/otg/dataset/study_locus.py
src/otg/gwas_catalog.py
src/otg/method/ld.py
src/otg/method/pics.py
tests/conftest.py
tests/dataset/test_study_locus.py
tests/method/test_ld.py
tests/method/test_pics.py
tests/test_spark_helpers.py

- bugfixes and tests necessary to have a successful run
- study_index logic changes: `update_study_id` doesn't use aliases to avoid ambiguous columns references
- ld logic changes: extraction of methods in the `annotate_ld` function to facilitate testing
- pics logic changes: refactor of the main functions to account for nullable credibleSets (when a variant can't be resolved to our index) and empty credibleSets  (when the variant can't be resolved to a reference panel)
It takes 2h7min to run, consistent with @DSuveges 's previous pipeline ([job](https://console.cloud.google.com/dataproc/jobs/my_gwas_catalog-jjh5kik3boefu/monitoring?region=europe-west1&project=open-targets-genetics-dev)).
The results can be investigated here:
- Study locus …

Debugging GWAS Catalog pipeline

---

src/otg/assets/schemas/study_locus.json
src/otg/common/gwas_catalog_splitter.py
src/otg/dataset/study_index.py
src/otg/dataset/study_locus.py

This PR closes [#2959](https://github.com/opentargets/issues/issues/2959)
1. Incorrect parsing for traitFromSource was due to null values of pValue Text. The parsing is done by using the artificial `subStudyDescription` column, which consists of the concatenation of `reported trait + p value text + efo`. The lack of the second element was causing the problem. Solved in https://github.com/opentargets/genetics_etl_python/commit/34d44aabe020a2de742df69c4f6d1605fd7cb8d0 and https://github.com/opentargets/genetics_etl_python/commit/94e1a82396e9c90cc27525420eea7fdce3975a7f
2. Incorrect parsing for traitFromSourceMappedIds was due to aberrant splitting of the `subStudyDescription` column again. We were using `_` to concatenate multiple EFOs, which is the same character we use to represent the …

Fix GWASCatalog data issues

---

docs/contributing.md
docs/index.md
docs/troubleshooting.md
utils/remove_pyenv_poetry.md

While committing the FinnGen sumstat ingestion changes, I encountered a very annoying bug with my pre-commit configuration. It wouldn't let me commit anything, throwing around some obscure errors with JavaScript tracebacks.
After some digging, it turned out the issue was a conflict between a system-wide NodeJS version, and a version pre-commit actually wanted. I've researched ways to fix this, and added instructions to the documentation.
I've also amended instructions for Pyenv/Poetry reinstallation to be more complete.
Finally, seeing as we now have four troubleshooting entries, I've reorganised them to occupy a separate page, `troubleshooting.md`

Amend and reorganise troubleshooting section

---

src/otg/assets/schemas/summary_statistics.json
src/otg/common/spark_helpers.py

As suggested by @DSuveges, we would like the `SummaryStatistics` to encode the `pValueMantissa` as `float` instead of `double` to adjust to the most appropriate resolution for this field.
This will ensure compatibility between the `SummaryStatistics` and the `StudyLocus` datasets. At the moment, both of them have a `pValueMantissa` field but are `DoubleType` and `FloatType` respectively.
@hlnicholls and @tskir you might want to pull this change to your branches once it's merged.

fix: pValueMantissa as float in summary stats

---

src/otg/dataset/ld_index.py
src/otg/method/ld.py

- changes to close [#3018](https://github.com/opentargets/issues/issues/3018)
**Note: the LDMatrix will suffer changes after recent discussion. However, we still want to capture the latest state of this dataset, since it is relevant for the GWAS Catalog StudyLocus one. And these filters will be propagated to the new LDIndex.**

Remove ambiguous variants from LDIndex

---

src/otg/dataset/study_locus.py
src/otg/method/ld.py

- fixes to close https://github.com/opentargets/issues/issues/3019
- changes to adjust the r2 threshold for the LD matrix to annotate all variants with a correlation of .2. The threshold of .5 is maintained once the r2Overall is calculated. __Note: allowing for a more flexible threshold didnt impact the step runtime.__
**As noted in https://github.com/opentargets/genetics_etl_python/pull/105, the function to annotate the LD set will change with the new LDIndex. These changes were mostly fixes on how to operate with the LDIndex. When the new dataset is in place, I expect that most of this logic will be affected (for the better).**

Fixes to the `annotate_ld` function

---

src/otg/common/session.py
src/otg/dataset/dataset.py
src/otg/dataset/gene_index.py
src/otg/dataset/variant_annotation.py
src/otg/dataset/variant_index.py
tests/common/test_gwas_catalog_splitter.py

This PR includes some suggestions from @DSuveges, that are now straightforward with the new abstract class:
- changes to allow for the use of kwargs in `Dataset.from_parquet`.
- I've tested it with `ds = GeneIndex.from_parquet(session, PATH, recursiveFileLookup=True)` 
- In general, any argument that can be passed to `spark.read.parquet(...)` can be used
- inclusion of `persist/unpersist` as Dataset methods.
- Tested it with ` ds.persist() / ds.unpersist()`. Both dfs are persisted/unpersisted, and the method returns the dataset child class.

Small new features for Dataset

---

config/datasets/gcp.yaml
config/step/my_study_locus_overlap.yaml
docs/components/dataset/study_locus_overlap.md
docs/contributing.md
src/otg/assets/schemas/study_locus_overlap.json
src/otg/config.py
src/otg/dataset/dataset.py
src/otg/dataset/study_locus.py
src/otg/dataset/study_locus_overlap.py
src/otg/gene_index.py
src/otg/method/colocalisation.py
src/otg/overlaps.py
tests/conftest.py
tests/dataset/test_study_locus.py
tests/dataset/test_study_locus_overlaps.py

This PR contains the code necessary to output a dataset of overlapping signals that share common variants in their credible sets.
The initial purpose was to help @xyg123 use this as part of his pattern based colocalisation. Based on the discussion, I've learnt today that this is not the case for 2 main reasons:
- At this stage of the process we don't have credible sets, as this is a preliminary step to identify common signals prior to finemapping
- The proposed method, SMR-Theta, calculates the overlaps by looking at all variants in the region - so it is distance-based, rather than LD-based.
So this definition of an overlap dataset will fit in a different branch of work, and will have its own specification in a separate ticket.
The scope of this specific dataset is then to generate data …

feat: add `StudyLocusOverlaps` step to the project

---

config/step/my_gwas_catalog.yaml
src/otg/assets/schemas/ld_index.json
src/otg/assets/schemas/study_locus.json
src/otg/config.py
src/otg/dataset/ld_index.py
src/otg/dataset/study_index.py
src/otg/dataset/study_locus.py
src/otg/gwas_catalog.py
src/otg/method/ld.py
src/otg/method/pics.py
tests/conftest.py
tests/dataset/test_study_index.py
tests/dataset/test_study_locus.py
tests/method/test_ld.py
tests/method/test_pics.py
workflow/dag.yaml

- Logic for the new LDAnnotator, based on the work described here https://github.com/opentargets/issues/issues/3020#issuecomment-1636053704
- Logic changes to assign an LD set to every GWAS Catalog curate study/locus pairs. We now have 2 fields to differentiate the result of expanding the locus (`ldSet`) from the variants that belong to the credible set (`credibleSet`). The latter one is a subset of `ldSet`. 
- Adaptation of PICS.finemap 
- Minor bugs
The new GWASCatalog step runs in 12 minutes (as opposed to > 2h previously) and it is much simpler to follow. 
Some stats from the latest data (available at `gs://genetics_etl_python_playground/output/python_etl/parquet/XX.XX/catalog_study_locus`)
- 434,351 associations
- 47,326 associations with a null ldSet because they …

New LD annotator for GWASCatalog curated studies

---

src/otg/common/gwas_catalog_splitter.py
src/otg/common/utils.py
src/otg/dataset/study_locus.py
src/otg/method/window_based_clumping.py

- minor changes to the GWASCatalog curation parsing that reassigns a new `studyLocusId` that is the product of hashing the variant and study columns
- the process involves creating a temporary `stuydyLocusId` necessary for the steps to parse the input data. At the end, once the studies are splitted, we assign this new final column.
Creating a consistent identifier is important for downstream processed like L2G.
**These edits are made having the `il-ld-annotator` branch as a base (currently under review)** 
New GWASCat index and associations datasets here:
```
gs://genetics_etl_python_playground/output/python_etl/parquet/XX.XX/catalog_study_index/
gs://genetics_etl_python_playground/output/python_etl/parquet/XX.XX/catalog_study_locus/
```

Assign final `studyLocusId` to GWASCat data

---

pyproject.toml
src/otg/assets/schemas/study_locus.json
src/otg/assets/schemas/study_locus_overlap.json
src/otg/common/schemas.py
src/otg/common/utils.py
src/otg/dataset/study_locus.py
src/otg/method/clump.py
src/otg/method/pics.py
tests/conftest.py
tests/dataset/test_study_locus.py
tests/method/test_clump.py
tests/method/test_pics.py

```      
"name": "is95CredibleSet",
"name": "is99CredibleSet",
"name": "logABF",
"name": "posteriorProbability",
"name": "variantId",
"name": "pValueMantissa",
"name": "pValueExponent",
"name": "pValueMantissaConditioned",
"name": "pValueExponentConditioned",
"name": "beta",
"name": "standardError",
"name": "betaConditioned",
"name": "standardErrorConditioned",
"name": "r2Overall",
```

Rename locus columns (no tags)

---

src/otg/method/pics.py
tests/method/test_pics.py

The formula used to calculate the PICS standard deviation was wrong due to the numerous parenthesis.
We were calculating this:
Instead of what [PICS defines](https://github.com/opentargets/genetics_etl_python/pull/112#issuecomment-1654101846):
I am extracting the absolute value of the st. deviation, because the survival function cannot be defined with negative values.
More details and context in this comment https://github.com/opentargets/genetics_etl_python/pull/112#issuecomment-1654101846

Correct formula for PICS standard deviation

---

src/otg/dataset/summary_statistics.py
src/otg/method/window_based_clumping.py

Ocassionally we want to apply a different threshold to do window based clumping and to collect locus around a semi index. This was not possible before. Now the two distances are de-coupled.

feat: flexible window set up for locus collection

---

src/otg/dataset/study_locus.py
src/otg/datasource/gwas_catalog/study_index.py
src/otg/method/ld.py
src/otg/method/pics.py
tests/method/test_pics.py

I'm not 100% sure this is the right thing to do... The LD set certainly can be resolved, but the subsequent r2Overall calculation fails. Adding the condition nullifies the LD set, but then we need to add an other QC metric to flag these special cases.
```python
(
study_index.df
.filter(f.col('ldPopulationStructure').isNull())
.select('studyId', 'ldPopulationStructure')
.show(20)
)
```
Out of 87,996 studies 12:
```
+------------+---------------------+
|     studyId|ldPopulationStructure|
+------------+---------------------+
|  GCST000218|                 null|
|GCST90093226|                 null|
|GCST90093235|                 null|
|  GCST000870|                 null|
|GCST90093223|                 null|
|GCST90102942|                 null|
|GCST90093229|                 null| …
```

Some studies just don't have population data causing LD annotation fail

---

docs/python_api/datasource/finngen/_finngen.md
docs/python_api/datasource/gnomad/_gnomad.md
docs/python_api/datasource/gwas_catalog/_gwas_catalog.md
docs/python_api/datasource/open_targets/_open_targets.md
docs/python_api/datasource/ukbiobank/_ukbiobank.md

As described in the [mkdocs documentation](https://www.mkdocs.org/user-guide/writing-your-docs/#linking-to-pages), while absolute paths might work in local deployment they are not supported and didn't work in the deployed docs.
This PR fixes the issue

issue with docs images

---

config/datasets/gcp.yaml
src/otg/assets/schemas/gene_index.json
src/otg/dataset/gene_index.py
src/otg/datasource/open_targets/target.py

In the process of running V2G I ran into minor issues with the gene index.
- Fix typo in the gene index output path
- Addition of missing columns of the target dataset that are used later in the project:
-  approvedSymbol
- approvedName
- biotype - used in V2G
- obsoleteSymbols
- with `obsoleteSymbols`, I propose a simplification of the schema. Impact is small. As a counterargument, we might not want to deviate from the target's original schema. Let me know your comments
- In the target we have an array of structs with `label` and `source`
- In my changes I propose to extract only the labels, so that we simply operate with an array of strings  
Output is herer `gs://genetics_etl_python_playground/output/python_etl/parquet/XX.XX/gene_index`

Add missing columns in gene index

---

docs/index.md
docs/python_api/dataset/gene_index.md
docs/python_api/dataset/study_index.md
src/scripts/schemadocs.py

Schemas for Gene and Study index were pointing to an obsolete filename.

fix(docs): schemas path for gene and study index

---

.github/dependabot.yaml

It should ensure the `src/airflow/Dockerfile` gets updates, but it hasn't been tested.

Dependabot to monitor airflow docker

---

src/airflow/dags/configs/dag.yaml

L2G's step was defined in the previous `workflow/dag`, and it was not ported in the transition to `airflow/dag`.
Adding the L2G and overlaps step to Airflow's DAG.

chore(dag): add l2g and overlaps steps to `dag.yaml`

---

tests/airflow/test_dag.py

Closes https://github.com/opentargets/issues/issues/3140.
For properly resolving all imports, we should change the working directory to `dags/` (which is the way Airflow does it in production), and since this wasn't done, the tests were failing.
Because we are using the `MonkeyPatch` class, directory is only changed for the import fixture and does not affect any other tests in the repository.

Re-enable and fix the `test_no_import_errors` Airflow DAG test

---

src/airflow/dags/common_airflow.py

This affects the way that args are provided for the pyspark job specification. 
DataprocSubmitJobOperator takes args as a list of strings. The previous function accepted a list of strings or a dictionary as inputs. When provided a dictionary, it'd parse it into a list of strings. In https://github.com/opentargets/genetics_etl_python/commit/930155765e7e7c474f877faad0018b329d977e79 I introduced a bug that incorrectly assumed that args were provided as a dict. If a list was provided, formatted_args would remain an empty array. This is actually the cause for the bug reported here https://github.com/opentargets/genetics_etl_python/pull/201#pullrequestreview-1706949353
I've changed it to only give support to have a list as input. It works now.

fix(airflow): job args are list of strings

---

pyproject.toml
tests/airflow/test_dag.py

Closes https://github.com/opentargets/issues/issues/3140 (again -__-)
After the fix in https://github.com/opentargets/genetics_etl_python/pull/218 it turned out that pytest's `DagBag` import and the actual Airflow deployment still differ in how they treat imports. In particular, "from . import airflow_common" imports work in pytest, but not in the actual Airflow set up.
After digging further, it looks like the proper way to make pytest evaluate those files is to extend its PYTHONPATH (_not_ PATH and _not_ the current working directory).
My apologies for the mix-up, the new configuration should now fix things for good.

A better way to fix DAG import test

---

src/airflow/dags/__init__.py
src/airflow/dags/common_airflow.py
src/airflow/dags/dag_genetics_etl.py
src/airflow/dags/dag_preprocess.py
src/otg/datasource/finngen/__init__.py
src/otg/datasource/finngen/summary_stats.py
src/otg/finngen.py
tests/datasource/finngen/test_finngen_summary_stats.py

Closes https://github.com/opentargets/issues/issues/3106.
* Added three new functions to the `common_airflow` module: `submit_step`, `read_yaml_config`, and `generate_dag`.
* Updated the ETL DAG to use these functions, making it even more readable and focused on logic.
* Implemented a new separate DAG for the Preprocess part, as we discussed.
* Made some refactoring changes specific to FinnGen ingestion.

Implement Preprocess DAG following recent architecture updates

---

src/airflow/dags/configs/dag.yaml
src/airflow/dags/dag_preprocess.py

Moving steps between DAGs is trivial.
- relocation of `variant_annotation` and `ldindex` steps to preprocessing dag, these are datasets that only need changing when a major gnomad version is released. They also happen to be the steps that require the most time to run
- this way we can tweak the ETL DAG without worrying about messing our input data
- On the flip side, it becomes less obvious to know the dependencies of our ETL steps
**Current ETL DAG:**
**Current Preprocessing DAG:**

feat(airflow): move `variant_annotation` and `ldindex` steps to preprocessing dag

---

docs/development/airflow.md
docs/development/workflows.md
src/airflow/dags/common_airflow.py

Closes https://github.com/opentargets/issues/issues/3142.
Now that https://github.com/opentargets/issues/issues/3145 is addressed, enabling autoscaling is easy ;-)
I have verified that it works using LD index as an example. I didn't run it to completion, but it has a very characteristic CPU load profile where we can immediately see the difference. On a single 96 core VM, graph width = 6 hours:
And on an a autoscaled cluster of 20 VMs (plot width = same 6 hours):
(@ireneisdoomed Sorry again for the clash, I didn't immediately realise you were running the step at the same time as I did — will be more vigilant going forward & change the output paths, etc.)
The cluster was very stable at 2 primary + 20 secondary workers (I even tested randomly killing a few secondary workers — it recovers …

Enable autoscaling, tune cluster parameters, add docs

---

src/airflow/dags/common_airflow.py

Python module path was malformed. It looked like `gs:.../.../gs:../.../.../` due to excessive concatenation of variables.
This fix should rescue all airflow runs. @ireneisdoomed came out with the same fix separately.

fix: wrong python file uri in airflow

---

utils/install_dependencies_on_cluster.sh

- a fix in `install_dependencies_on_cluster.sh` where the ensure the configuration of the project is downloaded to the root folder
Config was being extracted to a temporary folder. This implied that whenever we ran the task of installing dependencies on a cluster, the config wouldn't get updated.

fix: extract config in root when we install deps on cluster

---

src/otg/common/spark_helpers.py
src/otg/datasource/gnomad/ld.py
tests/datasource/gnomad/test_gnomad_ld.py

These are suggestions I had after https://github.com/opentargets/genetics_etl_python/pull/240 
- Improvements in set up fixtures of the tests
- Migration of `get_value_from_row` to common spark utils module
- Refactoring of `get_value_from_row`: nones are no longer handled within the function, it simply raises an error if the input is not a row. Nones are handled outside the context of the function
- Modification of how we extract the start and end rows: by using `get_top_ranked_in_window` we make sure that the returned object is always a dataframe. Its maximum size is 1, and the minimum is 0. In this case the window is the whole dataframe.
- Modification of  `get_ld_variants`s logic not to return a spark dataframe necessarily. We make sure that start/end values are only …

feat(ld): minor improvements to gnomad matrix methods

---

src/otg/gwas_catalog.py

- I've added calling `clump()` which got removed accidentally
- Removal of hail initialisation (on a side note, the fact that Hail was initialising despite having set `start_hail=False` makes me think that sessions are not overwritten.
- Minor style changes
The step runs in 20'

fix(gwas_catalog): clump associations, remove hail and style fixes

---

src/otg/gwas_catalog.py

This PR surpasses the behaviour described in https://github.com/opentargets/issues/issues/3152 
I've checked various studies and they look correct. The one reported in the issue:
```python
df = session.spark.read.parquet("gs://genetics_etl_python_playground/output/python_etl/parquet/XX.XX/credible_set/catalog_curated")
df.filter(f.col("studyId") == "GCST000058").select("studyId", "variantId").show()
+----------+--------------+                                                     
|   studyId|     variantId|
+----------+--------------+
|GCST000058|6_38473194_A_G|
+----------+--------------+
```

fix: persist raw gwascat associations to return consistent results

---

src/airflow/dags/common_airflow.py

@d0choa @ireneisdoomed @DSuveges Please see the results of evaluating various performance approaches in https://github.com/opentargets/issues/issues/3155.
This PR implements the only tangible performance improvement that actually helps: attaching local SSDs to instances. Airflow's `ClusterGenerator` does not support this natively, and the existing `num_local_ssds=1` which is passed to it does nothing.
However, by editing the resulting config directly we can achieve this.
Closes https://github.com/opentargets/issues/issues/3155.

Enable local SSDs for worker nodes

---

config/datasets/gcp.yaml
config/step/pics.yaml
docs/python_api/step/pics.md
src/otg/pics.py

New step to run PICS on study locus with annotated LD:
- [feat: new PICS step](https://github.com/opentargets/genetics_etl_python/commit/c9d8dd9d1dfc5e987080d8fecc43cbc8abda4a7a)
- [feat: configuration for PICS step](https://github.com/opentargets/genetics_etl_python/commit/0c5878c0546814d02ac076ea15031e3af3b7ff72)
- [docs: pics step](https://github.com/opentargets/genetics_etl_python/commit/e73732e322583253d36e5a97c01f6ffccb8e1fd6)
Similar to #258, this step is configured to run on all available study locus with annotated LD. However, I have used this step only to run finngen study locus as part of the preprocessing by parametrising the inputs and outputs. Different from all the steps we have done so far, clumping and pics could be reused for different inputs/outputs.
A successful run of …

New PICS step

---

src/airflow/dags/common_airflow.py

This PR adds parameters to airflow common functions in order to be able to:
- Parametrise autoscaling policy - different DAGs might have very different requirements
- Add task_id (airflow) different than the `step_id`. This allows the reuse of steps for different processes
- `other_args` in the submission of pyspark allows to parametrise the submission of a step (e.g. inputs/outputs)
- `trigger_rule` allows to specify that pyspark jobs might run on "ALL_DONE" instead of "ALL_SUCCESS". This is very powerful while developing. Combined with the spark `writemode`, it allows the running of subsequent steps even though the upstream tasks failed because the outputs were already available.
The logic exploiting these new parameters will come in different PRs

Extra parametrisation on airflow common

---

src/otg/dataset/dataset.py

This PR raises an error in `Dataset.from_parquet` if the file is found to be empty, preventing silent failures in data pipelines.
`isEmpty()` works by invoking `limit(1).count()`, which means that forces the evaluation of this operation in the Spark plan. I don't think this will have a major impact in the performance, and reading operations are done very early in the pipeline. And, if anything, the step will fail faster.
I've come across this bug a few times, most recently when accessing the credible set folder for L2G. I think that due to incompatible schemas from various sources, querying this folder returned an empty dataframe.

feat: raise error in `from_parquet` when df is empty

---

src/otg/common/utils.py
tests/conftest.py

The function that calculated the confidence interval was not taking into account the 95% z score.
This bugfix has no impact on the current data, as this is a function we were not using at the moment.

fix: multiply standard error by zscore in `calculate_confidence_interval`

---

src/otg/datasource/gwas_catalog/study_splitter.py
tests/datasource/gwas_catalog/test_gwas_catalog_study_splitter.py

The source of the error where studies were split even though the metadata was the same resided in the `_resolve_study_id` logic.
This function windows over each study and sorts by "subStudyDescription", which is the column that contains the metadata for splitting. You can see the problem very clearly here:
```
+----------+---------------------------------------------+-------------+---------+--------------+
|studyId   |subStudyDescription                          |subStudyCount|rowNumber|updatedStudyId|
+----------+---------------------------------------------+-------------+---------+--------------+
|GCST003436|Endometrial cancer|no_pvalue_text|EFO_1001512|4            |1        |GCST003436_1  |
|GCST003436|Endometrial cancer|no_pvalue_text|EFO_1001512|4            |1        |GCST003436_1 …
```

Il fix studies split

---

src/otg/clump.py

The tree structure for summary stats requires reading files recursively.

fix(clump): read input files recursively

---

templates/.release_notes.md.j2
templates/CHANGELOG.md.j2

Proposed changes modify the changelog from the current one...
to the new one...
(I'm not the most skilled jinja 🥷 programmer)

feat: new changelog and release notes templates 

---

src/otg/dataset/l2g_feature_matrix.py
src/otg/method/l2g/evaluator.py
src/otg/method/l2g/model.py
tests/dataset/test_l2g.py

- change to `calculate_feature_missingness_rate` to count as incomplete studyLoci where the extracted feature has a value of 0.0
- `calculate_feature_missingness_rate` test
- minor typing improvements related to wandb
In the latest run with the newer VEP features, missingness for all available features was 0. This is incorrect, there is a preliminary step in the L2G's matrix where I fill all nulls with 0s. So only taking nulls into consideration is not valid.

fix(l2g): `calculate_feature_missingness_rate` counts features annotated with 0 as incomplete

---

src/airflow/dags/common_airflow.py

Closes https://github.com/opentargets/issues/issues/3184.
We decided that half an hour is a sensible amount of time to allow the cluster to be idle: in a debugging mode, it allows the developer to fix the issue and restart without recreating the cluster; while in a failsafe mode, it will stop the cluster after running idle for any meaningful amount of time.

chore: set cluster delete TTL

---

src/otg/assets/schemas/study_locus.json
tests/conftest.py

- deletion of the variant statistics after conditioning from the StudyLocus schema
Inside a `locus`, we have a couple of statistics that describe the association between a variant and the trait after doing conditional analysis.
COJO does conditioning, and that is why we were maintaining these fields. However our current implementation does not include adjusting the p values based on other signals in the locus.
Given the current size of our locus object, I think we're better off without these null fields polluting the codebase.

feat(study_locus): remove statistics after conditioning from schema

---

src/airflow/dags/finngen_preprocess.py

to align it with `gwas_catalog_preprocess.py`

chore: change picsed finngen outputh path

---

pyproject.toml
src/otg/__init__.py

This is falling out of fashion when using modern build systems (e.g. poetry). More info here:
https://stackoverflow.com/questions/72167802/adding-version-attribute-to-python-module

fix: deprecate __version__ in __init__.py

---

.github/workflows/release.yaml
README.md
docs/index.md
mkdocs.yml
pyproject.toml

These changes are necessary for renaming the GitHub repo from `genetics_etl_python` to `gentropy`

refactor: rename genetics_etl_python to gentropy

---

.github/dependabot.yaml

This PR only ignores patch releases from Dependabot. (not tested)
I didn't change the time of the week, I'll leave it up to you @ireneisdoomed.

ci: ignore patch versions in dependabot

---

docs/howto/python_api/d_inspect_dataset.md
docs/src_snippets/howto/python_api/d_inspect_dataset.py
src/gentropy/dataset/dataset.py
tests/dataset/test_dataset.py
tests/docs/test_inspect_dataset.py

The new `Dataset.filter` util was a request of @DSuveges. It is useful to apply filters on the data while maintaining the datatype.
Important to note that this solutions creates different versions (instances) of the dataset. More specifically, as many instances as filters we apply. 
I've added the method to the User Guide docs.

feat(dataset): add `Dataset.filter` to create a new dataset instance with filtered data

---

docs/python_api/methods/susie_inf.md

In `https://opentargets.github.io/gentropy/python_api/method/susie_inf/`
with these changes doing `poetry run mkdocs serve`

docs: susie inf method reloacated with the rest of the methods

---

.github/workflows/pr_release_trigger.yaml

This automation hopefully triggers a PR from dev to main every Thursday at 4pm GMT.

ci(release): add action to open pr that triggers release weekly

---

utils/install_dependencies.sh

When running `make setup-dev` the pre-commits are updated using the auto-update functionality. This is not a good idea as any time someone installs a local environment it pollutes that branch with updates in the pre-commit hooks and breaks the 1 branch -> 1 feature rule.
This was observed in #515 
Remove pre-commit autoupdate from make setup-dev

fix: make setup dev not to update pre-commits

---

src/gentropy/assets/schemas/l2g_feature_matrix.json
src/gentropy/config.py

After the work in https://github.com/opentargets/issues/issues/3235, we have colocalisation results between gwas and pQTLs, sQTLs and tuQTLs that can be used in L2G.
This PR adapts the configuration to include the new analyses. Mainly:
- Update L2GFeatureMatrix schema
- Update L2G features list inclusion list so that the model is trained using the full set of features
A nicer implementation of this where the FM schema doesn't need to be adjusted (https://github.com/opentargets/issues/issues/3146)

chore(l2g): update inclusion features list with newer QTLs

---

src/gentropy/method/susie_inf.py
tests/gentropy/method/test_susie_inf.py

Small PR that fixes defaults in SuSiE to canonical ones.
It switches off the estimation of inf effects as a default.
-

fix: small fixes in susie defaults

---

src/gentropy/method/colocalisation.py
tests/gentropy/method/test_colocalisation_method.py

Testing COLOC's behaviour when Bayes Factors aren't present I observed that null values of logBF weren't filled with 0:
```
+----------------+-----------------+----------+------------+------------+
|leftStudyLocusId|rightStudyLocusId|chromosome|tagVariantId|  statistics|
+----------------+-----------------+----------+------------+------------+
|               1|                2|         1|         snp|{null, null}|
+----------------+-----------------+----------+------------+------------+
df.fillna(0, subset=["statistics.left_logBF", "statistics.right_logBF"]).withColumn(
"sum_log_bf",
f.col("statistics.left_logBF") + f.col("statistics.right_logBF"),
).show()
+----------------+-----------------+----------+------------+------------+----------+ …
```

fix(coloc): handle cases when the bayes factors are null

---

src/gentropy/datasource/finngen/summary_stats.py

When input is a directory the study ids are not read correctly for finngen sumstats.
Extract finngen `study_id` by using `f.input_file_name()` instead of `study_id = raw_file.split("/")[-1].split(".")[0].upper()`.

fix(sumstats): correct study id for dir of finngen studies

---

src/gentropy/susie_finemapper.py

Allows `SusieFineMapperStep` to run directly on a `study_locus_row` that has already had the gwas summary statistics for the locus annotated with `StudyLocus.annotate_locus_statistics()`

feat: susie_finemapper_ss_gathered()

---

notebooks/FineMapping_AlzheimierDisease.ipynb

This PR presents an example of fine-mapping of the GWAS catalog study for Alzheimer's disease ([link to study](https://genetics.opentargets.org/Study/GCST90012877/associations)). The study itself is a good benchmarking example for fine-mapping - relatively large number of SNPs, very strong signal on the 19th chromosome (APOE). It's worth noting that usually very strong signals are excluded from fine-mapping due to instability.
Summary:
- 10607272 SNPs in GWAS
- 33 clumps (32 without MHC)
- Fine-maping of all 32 clumps (without MHC) on my local machine using one cpu and a 2Mb window: 95 min (~3 min per locus). This run was performed without carma and sumstat imputation. 
- The average number of overlapping SNPs between GWAS and LD was 6653.3125 SNPs.
- The complete fine mapping run of the …

feat: add benchmarking for fine-mapping using Alzheimer as example

---

src/gentropy/susie_finemapper.py

Some sumstats files have duplicated variant rows, where it isn't clear which is the correct entry. This causes errors in the finemapping pipelines, specifically when extracting the gnomad blockmatrix. 
adds a few lines to remove ALL variants that appear more than once in the sumstats prior to finemapping.

fix: removing all duplicated variants in sumstats for finemapping functions

---

notebooks/Mapping_EFO_finngen.ipynb

Mapping EFOs for the FinnGen study index using old study index from the previous prod.
This notebook adds EFOs from previos prod version of study_index to the new FinnGen study_index using trait name as a matching key.
The rsulting study index has 1542 rows with not null EFOs (out of 2408 rows).
The new study index is saved here:
"gs://genetics-portal-dev-analysis/yt4/study_index_finngen_with_efo"

feat: adding notebook for mapping EFOs for the FinnGen study index

---

Dockerfile

Dockerfile to dockerise the python application. Image can be built using:
```
docker build . --tag gentropy_app
```
Steps can be run using:
```
docker run gentropy_app
```
- Slimming down the image size
- Github action to automatically build the image
- Unit test image build is correct

feat: dockerise gentropy python package

---

src/gentropy/config.py
src/gentropy/susie_finemapper.py

feat: updating step config file

---

src/gentropy/config.py

Updated finemapper argument name in config

fix: updating config.py argument for finemapper

---

.github/workflows/artifact.yml

It would be handy to have a gentropy image of the dev branch available in GCP at all times.
This GitHub Action aims to build the image of gentropy from the Dockerfile and upload it to the GCP Artefact Registry.
- I can't make sure the action runs properly locally. It's using the secrets in GitHub. It's unlikely to work in the first shot
- It only deploys the dev branch for now. We could have docker images for each release as well if this works.

feat: github action to upload docker image to artifact registry

---

Dockerfile

The current Docker image is a bit naive and takes a lot more space than needed. Some dependencies like hail-compatible Java are not there. Also, the code and the dependencies are in different layers which results in much faster build times.
- A lighter docker image with more defined layers.
- Java 11 is installed for hail compatibility
- CI/CD image

fix: Java 11 in docker image and lighter image 

---

.github/workflows/release.yaml

Version requires "v" before number

fix: fix python-semantic-release version (again)

---

src/gentropy/common/spark_helpers.py

Upon using `gentropy.common.spark_helpers.order_array_of_structs_by_field` I encountered the following exception:
```
24/05/19 23:17:07 ERROR Utils: Aborting task
java.lang.IllegalArgumentException: Comparison method violates its general contract!
```
which  occurs when the comparison function used in sorting is not transitive, i.e., it does not consistently return the correct ordering of elements. Unfortunately I couldn't reproduce an atomic use case to demonstrate the implicated condition. The core logic:
```python
return f.expr(
f"""
array_sort(
{column_name},
(left, right) -> case
when left.{field_name} is null then 1
when right.{field_name} is null then -1
when left.{field_name} < right.{field_name} then 1
when left.{field_name} > right.{field_name} then -1
else 0
end)
"""
)
```
The …

fix(spark helpers): sorter function updated to avoid crash

---

.gitignore
Makefile
config/datasets/ot_gcp.yaml
config/step/ot_ld_index.yaml
config/step/ot_variant_annotation.yaml
docs/python_api/_python_api.md
docs/python_api/common/_common.md
docs/python_api/common/types.md
docs/python_api/common/version_engine.md
pyproject.toml
src/gentropy/common/types.py
src/gentropy/common/version_engine.py
src/gentropy/config.py
src/gentropy/datasource/gnomad/ld.py
src/gentropy/datasource/gnomad/variants.py
src/gentropy/ld_index.py
src/gentropy/variant_annotation.py
tests/gentropy/common/test_version_engine.py

The context is described in https://github.com/opentargets/issues/issues/3324.

feat(config): gnomAD steps configuration extraction and versioning

---

src/gentropy/datasource/gnomad/ld.py

Finemapping relies on the `ld` module to perform some operations. This module has an error in its static method, `get_numpy_matrix`.
This is a simple fix to ensure the static method works. Note that this is not the most elegant possible solution; it is possible that a static method could be replaced with a better approach, but this is outside the scope of this simple fix PR.

fix(ld): correct syntax for the `get_numpy_matrix` static method

---

src/gentropy/susie_finemapper.py

The new version of finemapping, when ran with _logging=True,_ outputs some statistics into a dataframe. However, there's a syntax bug preventing the pipeline from completing.
This PR fixes the syntax for outputting the logging dataframe.

fix(susie_finemapper): correct syntax for saving the logs df

---

src/gentropy/susie_finemapper.py

Fix in the fine-mapper in case of sum stat imputation is False.
It doesn't load the whole matrix.

fix(susie_finemapper): fix in the fine-mapper in case of sum stat imputation is False

---

src/gentropy/dataset/dataset.py
src/gentropy/dataset/summary_statistics.py
tests/gentropy/dataset/test_dataset.py
tests/gentropy/method/test_qc_of_sumstats.py

This PR adds filtering by inf in summary statistics.

fix(SummaryStatistics): fix in sanity_filter

---

config/step/ot_window_based_clumping.yaml
src/gentropy/config.py
src/gentropy/dataset/summary_statistics.py
src/gentropy/datasource/gwas_catalog/associations.py
src/gentropy/finemapping_simulations.py
src/gentropy/method/window_based_clumping.py
src/gentropy/window_based_clumping.py

https://github.com/opentargets/issues/issues/3327
This is the first part of the #3327. 
* Extraction of the `gwas_significance` (p-value) threshold parameter for the window-based-clumping step.
* Addition of `gwas_significance` to the airflow config with the new value (`1e-8`) overwriting default one (`5e-8`)
* Unified naming convention for the `WindowBasedClumpingStep` config to `WindowBasedClumpingStepConfig`
The main reason for this change is that we want to use the value of `1e-8` and possibly even more stringent value of `1e-9` in the future.

feat(config): extract gwas_significance parameter to step configuration

---

src/gentropy/dataset/l2g_feature_matrix.py
src/gentropy/dataset/l2g_prediction.py
src/gentropy/dataset/pairwise_ld.py
tests/gentropy/dataset/test_l2g.py

During the 24.06 data release results check team found `feature_matrix` published at 
```
gsutil du -sh gs://genetics_etl_python_playground/releases/24.06/locus_to_gene_feature_matrix
10.16 GiB    gs://genetics_etl_python_playground/releases/24.06/locus_to_gene_feature_matrix
```
The resulting table schema 
```
root
|-- studyLocusId: long (nullable = true)
|-- geneId: string (nullable = true)
|-- distanceTssMean: float (nullable = true)
|-- distanceTssMinimum: float (nullable = true)
|-- eqtlColocClppMaximum: float (nullable = true)
|-- eqtlColocClppMaximumNeighborhood: float (nullable = true)
|-- eqtlColocLlrMaximum: float (nullable = true)
|-- eqtlColocLlrMaximumNeighborhood: float (nullable = true)
|-- pqtlColocClppMaximum: float (nullable = true)
|-- pqtlColocClppMaximumNeighborhood: …
```

fix(L2GPrediction): schema validation

---

src/gentropy/datasource/gnomad/ld.py
src/gentropy/susie_finemapper.py

This PR adds new fine-mapper function that takes locus boundaries as input.

feat(SusieFineMapperStep): add new function with boundaries

---

src/airflow/dags/common_airflow.py

Sometimes it is very useful to be able to spin up a Jupyter notebook on a Dataproc cluster which has access to Gentropy and all its configured environment. Previously, I already added the “enable_component_gateway” option; however, it doesn't really take any effect unless you also specify the list of components to enable, which is what I'm doing in this PR.
Enable Jupyter Notebook component for the cluster.
N/A.

chore: enable Jupyter Notebook gateway for the Dataproc cluster

---

src/gentropy/susie_finemapper.py

Code inspection shows that it is not used anymore.
Recent changes in `SusieFineMapperStep` left a parameter `locus_radius` which is not used anymore.
Remove the unused parameter locus_radius.
N/A

chore(SusieFineMapperStep): remove the locus_radius parameter

---

src/gentropy/config.py

There is a typo in the `cs_lbf_thr` parameter name in the `FinemapperConfig` class. This causes problems when trying to define while triggering a Google Batch job.
Fix the typo.
N/A.

fix: typo in `cs_lbf_thr` parameter name

---

src/gentropy/config.py

In some cases, we need to override configuration values from the CLI.
`extended_spark_conf` is a `dict[str,str] | None`, but it is None by default. Because of that, when you try to override or add any keys, you get the following exception:
```
AttributeError: 'NoneType' object has no attribute 'get'
full_key: step.session.extended_spark_conf
reference_type=Optional[Dict[str, str]]
object_type=NoneType
```
Instead of being `None`, `extended_spark_conf` is now an empty dict. This does not change anything for the existing code and use cases, but allows us to override it from the CLI.
N/A

fix: make extended_spark_conf an empty dict instead of None

---

src/gentropy/config.py

As it is, when the susie_finemapper step is triggered, nothing happens because the configuration class is not linked via _target_ to the step class.
Address the problem by linking the classes via the _target_ parameter.
N/A.

fix(SusieFineMapperStep): link configuration and step classes

---

src/gentropy/config.py

Two values were recently removed from the step in https://github.com/opentargets/gentropy/pull/679.
This brings config in alignment with these changes.
N/A

fix(finemapping): reconcile changes in the finemapping step with config

---

.github/workflows/pr_release_trigger.yaml

The last release (v1.4) I have rebased the dev -> main branch in PR https://github.com/opentargets/gentropy/pull/619 , which let us to have conflicting branch histories between main and dev. This PR removes the word "REBASE" from the PR label.

ci: prevent user from rebasing in minimal way

---

src/gentropy/common/spark_helpers.py
src/gentropy/datasource/open_targets/variants.py
tests/gentropy/datasource/open_targets/test_variants.py

This PR corresponds to the work of including Platform datasets to enrich the new variant index. It is secondary to #678 
@DSuveges identified during his review that when we processed the Gentropy credible sets, we weren't exploding the variants in the locus.
This PR adds and tests that functionality
- Not present columns are handled with a common method so that the same step is applicable to all input dfs
- Addition of `create_empty_column_if_not_exists`
- Unit tests for all scenarios: df with only variant IDs, df with only rsIDs, df with a defined locus

fix(variants): explode loci to generate list of variants + tests

---

src/gentropy/susie_finemapper.py

Finemapping outputs logs as part of its run.
Fix the typo in the finemapping logs output: `eleapsed_time` to `elapsed_time`.
N/A

fix(finemapping): typo in "elapsed_time"

---

src/gentropy/config.py
src/gentropy/susie_finemapper.py

Google Batch has issues submitting large payloads. In theory the maximum payload is 10 MB, but in practice environment lists of more than approximately 4,000 tasks per batch job fails.
Study locus input and output paths are being read from the CSV manifest, and only the index of a row needs to be specified, which can be done with a predefined `$BATCH_TASK_INDEX` variable.
N/A.

feat: implement reading study locus paths from the manifest

---

.github/workflows/release.yaml

This PR is continuation of testing release of the gentropy Docker image with specific tag, when release is triggered - for more detail check https://github.com/opentargets/issues/issues/3384

ci(release): use github app token for tag push

---

docs/python_api/steps/locus_breaker_clumping.md
docs/python_api/steps/summary_statistics_qc.md
src/gentropy/config.py

This PR implements https://github.com/opentargets/issues/issues/3398
manual test of the command `poetry run gentropy`

feat: expose summary statistics qc and locus breaker steps to hydra cli

---

src/gentropy/config.py
src/gentropy/method/carma.py
src/gentropy/susie_finemapper.py

This PR fixes the bug with CARMA reported by Kirill (NaN in probabilities). 
It adds the parameter to FineMapper. The error turned out to be a problem with LD and increasing this parameter helps to overcome it reducing the sensitivity of the method.

fix: adding carma_tau parameter to susie_finemapper

---

src/gentropy/common/harmonise.py
src/gentropy/datasource/ukb_ppp_eur/summary_stats.py

This is the first PR in a series of three to implement FinnGen UKB meta-analysis ingestion.
Previously, per-chromosome processing and harmonisation routines were implemented specifically for UKB PPP data.
This series of PRs generalises those routeines to make them reusable, and builds FinnGen UKB meta-analysis ingestion on top of those changes.
Generalise the harmonisation pipeline:
* Move into a separate module
* Make column names configurable
* Make some column names optional
N/A

refactor: generalise the harmonisation pipeline

---

.github/workflows/artifact.yml

There are two problems with Docker builds:
* They take about 11 minutes per commit;
* They only happen for the `dev` branch and `v*` tags.
It is desirable to automatically build the image for other branches, so that a version in development could be run for example on Google Batch. However, with 11 minutes per commit it's not very convenient.
Add a step to quickly build a Docker image for every branch, which means:
* Only build the main gentropy image;
* Only do it for the AMD64 architecture required for Google cloud;
* Use maximum layer caching through GHA.
With this change, build takes around 1–2 minutes per commit (depending on whether dependencies were changed or not) instead of 11. This is now trivial to run for every commit of every branch.
The full builds, which include ARM64 …

perf: quickly build a Docker image for every branch

---

src/gentropy/dataset/study_locus.py
src/gentropy/datasource/gwas_catalog/associations.py
src/gentropy/datasource/gwas_catalog/study_splitter.py
tests/gentropy/datasource/gwas_catalog/test_gwas_catalog_associations.py

Closes opentargets/issues#3487
The only tricky decision here was where to place the QC flagging. I did it at the very end of the pipeline as `StudyLocusGWASCatalog` specific logic.

feat: flag all top-hits from GWAS catalog curation

---

src/gentropy/dataset/summary_statistics.py
src/gentropy/method/sumstat_imputation.py

Some refs were broken and mkdocs was throwing WARNINGS. This fixes it.
We could activate the ["strict" mode](https://github.com/opentargets/gentropy/blob/6ede7363c683d0955edafc647c9d13b2baf17fc7/tests/gentropy/docs/test_build.py#L19) on the mkdocs test if we want to prevent this in the future. For some reason, I thought this was too harsh in the past but maybe we could reconsider. I'll leave it up to you @project-defiant

docs: update broken refs

---

src/gentropy/config.py

This PR fixes issue with the `ColocalisationStep` that was updated with https://github.com/opentargets/gentropy/pull/782, but did not include the removal of the `study_index_path` from the hydra configuration.

fix: remove study_index_path from coloc step

---

src/gentropy/common/spark_helpers.py
src/gentropy/config.py
src/gentropy/dataset/variant_index.py
src/gentropy/datasource/open_targets/variants.py

This PR closes https://github.com/opentargets/issues/issues/3551

fix(safe_array_union): allow for sorting nested structs

---

src/gentropy/common/spark_helpers.py

There was a bug in spark_helpers in neglog_pvalue_to_mantissa_and_exponent - incorrect formula. Was spotted due to discrepancies in susie.

fix: bug in neglog_pvalue_to_mantissa_and_exponent

---

src/gentropy/config.py
src/gentropy/sumstat_qc_step.py

Currently `study_id` is a required parameter for running the `summary_statistics_qc` step. This is not ideal, as when running in bulk, we can not specify which study_id should be used to create the qc output path. 
The path to QC should be fully configurable, without it's part being hardcoded.

chore: drop redundant parameter from sumstat qc step

---

src/gentropy/assets/schemas/study_index.json
src/gentropy/dataset/study_index.py
src/gentropy/study_validation.py
tests/gentropy/dataset/test_study_index.py

Fixes a bug in the study validation where checking studies for biosample index would drop all GWAS studies. Also implements additional testing to catch this scenario in the future.
Changed the logic of the biosample_index study validation slightly to match the gene_index study validation a bit closer. Also modified the TestGeneValidation suite to be more abstract and inclusive i.e. be applicable to any study validation that is only for QTLs.
One function is duplicated instead of abstracted as the amount of code written was similar so I thought perhaps better to keep simple.

feat: fix biosample study validation

---

src/gentropy/dataset/study_locus.py
tests/gentropy/dataset/test_study_locus.py

As discussed with @addramir, we will want to discard all credible sets overlapping with SuSiE regions no matter whether we have LD information or no.
(Before we were rescuing PICS hits when no-LD is available)
We are going for the most conservative option for now.

revert: no longer rescuing variants not in LD matrix when overlapping with SuSiE

---

src/gentropy/variant_index.py

There are some issues with variant index partitioning:
- As mentioned by @jdhayhurst in opentargets/issues#3567, using the `partitionBy` strategy for writing the `variantIndex` implies that we need to infer the type of the `chromosome` column which can be problematic.
- The dataset is partitioned in too many small parts (4.9k objects for a total of 2.0 GiB)
- The positions are sorted alphanumerically which is also not ideal:
```
|115700605|
|115701247|
| 11958647|
|119621629|
| 11964316|
| 11966298|
| 11970804|
| 11970806|
|119712012|
|119743899|
|119759154|
|119759915|
| 11976200|
|119764157|
```
This PR reverts the `partitionBy` strategy and changes it to a partitionByRange + sortWithinPartitions
```
In [29]: df.repartitionByRange("chromosome", …
```

feat: enhance variant index partitioning

---

src/gentropy/config.py
src/gentropy/l2g.py

@d0choa observed a Java memory issue when running the L2G training
```
Caused by: [CIRCULAR REFERENCE: org.apache.spark.SparkException: Cannot broadcast the table that is larger than 8GB: 13 GB]
```
(more [here](https://console.cloud.google.com/dataproc/jobs/4941c761-4200-4ade-8555-f2353dcb1b7d/monitoring?region=europe-west1&authuser=1&project=open-targets-genetics-dev))
The L2G training step had a custom session that provided more memory to the cluster. This was inherited from the previous L2G version where this step included the feature matrix generation and the training was happening in Spark.
Because L2G is now a much lighter step, the default spark configuration should be enough.
- Removal of the session parameter in the `LocusToGeneStepConfig` that extended the spark configuration. …

fix(l2g): remove custom session params + other fixes

---

src/gentropy/colocalisation.py
src/gentropy/config.py
src/gentropy/dataset/colocalisation.py
src/gentropy/method/colocalisation.py
tests/gentropy/dataset/test_study_index.py
tests/gentropy/method/test_colocalisation_method.py
tests/gentropy/step/test_colocalisation_step.py
utils/install_dependencies.sh

The PR https://github.com/opentargets/gentropy/pull/830 added `prior` required arguments to the `ColocalisationStep`. As the step uses the `colocalisation_method` to evaluate which coloc method to use (Coloc or ECaviar), passing the required `prior` arguments to the `ColocaliseMethod.coloc()` will result in a bug within the `ECaviar` method, that does not require these parameters.
This PR attempts to fix the issue by 
- coloc_path = "gs://ot_orchestration/releases/24.10_freeze2/colocalisation"
- cs_path = "gs://ot_orchestration/releases/24.10_freeze2/credible_set"
The default behavior of the Coloc method is to use the provided `colocalisation_method_parameters` if passed, else it fallbacks to the default values:
- `priorc1` = 1e-4
- `priorc2` = 1e-4
- `priorc12` = 1e-5
Example how to run …

feat(coloc): step refactoring

---

src/gentropy/datasource/ensembl/api.py

Ensembl's API call fails sometimes, making the test crash. This PR doesn't remove the test, just tells pytest to skip it.
````
----> 1 fetch_coordinates_from_rsids(["rs75493593"])
File ~/MEGAsync/EBI/repos/gentropy/src/gentropy/datasource/ensembl/api.py:91, in fetch_coordinates_from_rsids(rsids, batch_size, pause_time)
88         all_results.update(_parse_response(variant_data))
90     except Exception as e:
---> 91         raise Exception(f"Error processing batch {i // batch_size + 1}: {e}") from e
93     time.sleep(pause_time)
95 return all_results
Exception: Error processing batch 1: HTTP Error 500: Internal Server Error
```

test: skip `fetch_coordinates_from_rsids`

---

src/gentropy/susie_finemapper.py

After successful run of ukb_ppp_eur finemapping we spotted, that the finemapping logs were saved along with the finemapping outputs - see [thread](https://github.com/opentargets/orchestration/pull/39#issuecomment-2408051745).
This is not ideal and requires moving the logs after the finemapping is finished, which due to the number of files, takes significant amount of time ~30 minutes of `GCSToGCSOperator`.
To address this issue we want to save the logs into a separate directory.

feat(susie_finemapper): allow for extraction of the log file from manifest

---

src/gentropy/dataset/study_locus.py
tests/gentropy/dataset/test_study_locus.py

Adding chromosome validation flag

chore: add chromosome validation

---

src/gentropy/dataset/l2g_features/distance.py
tests/gentropy/dataset/test_l2g_feature.py

This PR closes https://github.com/opentargets/issues/issues/3587
- We divide the distance features by log10(500_000+1) to keep them in a range between 0 and 1.

feat(l2g): normalise distance features

---

docs/python_api/steps/credible_set_qc_step.md
src/gentropy/config.py
src/gentropy/credible_set_qc.py
src/gentropy/method/susie_inf.py
tests/gentropy/step/test_credible_set_qc.py

The CredibleSetQC step required tests to see if it works correctly.

test(study_locus) credible_set_qc step integration test

---

src/gentropy/dataset/dataset.py
src/gentropy/study_locus_validation.py
tests/gentropy/dataset/test_study_index.py
tests/gentropy/dataset/test_study_locus.py

The duplication flagging is updated to keep one of the duplicates unflagged. + test.
There's no need to change configuration, as the ETL config already list the flag for [passing qc.](https://github.com/opentargets/orchestration/blob/60724899ca1b9b440c505ff19508f44de2b85bc1/src/ot_orchestration/dags/config/genetics_etl.yaml#L65-L66)

feat: flagging duplicated entries while keeping one of the duplicates

---

src/gentropy/assets/schemas/l2g_predictions.json
src/gentropy/dataset/l2g_features/other.py
src/gentropy/dataset/l2g_prediction.py
src/gentropy/l2g.py

A simple extension of the l2g step to add feature matrix to l2g prediction table. As such the following updates were made:
- Schema of l2g prediction is updated to have an extra optional column to contain features as a map.
- l2g prediction dataset is extended with a method to enrich dataset with the provided features.
- l2g step is extended with calling the above method.

feat: adding l2g features to prediction table

---

src/gentropy/variant_index.py
tests/gentropy/step/test_convert_to_vcf_step.py

The output from `convertToVcf` step uses the `csv writer` which can not write the `#CHROM` column correctly to the output csv file, as writer quotes the column, so the result is `"#CRHOM"`. This PR resolves this in a temporary solution, by removing the hash, that will be readded before the vep command is executed in the orchestration.

fix: ensure the #CHROM is not quoted

---

src/gentropy/l2g.py

This PR changes the `LocusToGeneFeatureMatrixStep` step to write only annotation for credible sets from GWAS. This is based on a conversation with @addramir, for now we are not planning to use this dataset for associations that don't have a L2G.
Dataset: `gs://ot-team/irene/l2g/05112024/feature_matrix_filtered`
The filter reduces the size of the dataset from 7Gb (103,256,085 rows) to 730Mb (18,991,756 rows). I haven't measured it, but the step is also significantly faster to generate.
The issue of the distance scores > 1 is also gone.

feat(feature_matrix): extract features for gwas associations only

---

src/gentropy/dataset/l2g_feature_matrix.py
tests/gentropy/dataset/test_l2g_feature_matrix.py

fix: do not impute `isProteinCoding`

---

src/gentropy/study_locus_validation.py

The current credible sets after validation are completely shuffled. This can have a performance cost in all downstream processes.
```
In [7]: cs.select("chromosome", "position").show()
+----------+---------+
|chromosome| position|
+----------+---------+
|         2|151525381|
|         1|162388605|
|        10|102449815|
|         2| 47169327|
|        21| 42298501|
|         8| 85157259|
|         1| 11838976|
|        20| 45919050|
|         2|106566631|
|        16| 14889311|
|         1| 17005181|
|         2| 99176335|
|         1|149185498|
|         X|  1661217|
|         X|   312722|
|        11|   807149|
|        10| 79836221|
|         2| 73063040|
|        14| 55647604|
|         5| 43001499|
+----------+---------+
only showing top 20 rows
```
To improve the partitioning, this …

feat: improve partitioning of credible sets

---

src/gentropy/l2g.py

The evidence datasets are all in packed ndjson format.
```
☁  orchestration [783f989] ⚡  gsutil ls gs://open-targets-ppp-releases/24.09dev/input/evidence-files
gs://open-targets-ppp-releases/24.09dev/input/evidence-files/
gs://open-targets-ppp-releases/24.09dev/input/evidence-files/atlas.json.bz2
gs://open-targets-ppp-releases/24.09dev/input/evidence-files/cancerbiomarkers.json.gz
gs://open-targets-ppp-releases/24.09dev/input/evidence-files/chembl.json.gz
gs://open-targets-ppp-releases/24.09dev/input/evidence-files/clingen.json.gz
gs://open-targets-ppp-releases/24.09dev/input/evidence-files/cosmic.json.gz
gs://open-targets-ppp-releases/24.09dev/input/evidence-files/crispr.json.gz
gs://open-targets-ppp-releases/24.09dev/input/evidence-files/crispr_screen.json.gz …
```

feat: gzip evicence output to match existing format

---

src/gentropy/config.py
src/gentropy/datasource/gnomad/variants.py
src/gentropy/gnomad_ingestion.py

The new dataset is saved here: `gs://gnomad_data_2/v4.1/variant_index`, confirmed that the allele frequencies are concordant with the GnomAD UI joint frequencies.

chore(gnomad): updating GnomAD version to 4.1 from 4.0 + using joint frequencies

---

src/gentropy/assets/schemas/l2g_gold_standard.json
src/gentropy/dataset/l2g_feature_matrix.py
tests/gentropy/dataset/test_l2g_feature_matrix.py

This PR adds the EFO ID to the gold standard so that we can split the training set by EFO/Gene during cross validation.
The change in the schema doesnt have implication in FE/BE as discussed.
Bare in mind this will create some explosion in the gold standard.
A following PR will make more thorough changes in the schema of the gold standard, and in the code to accommodate this dataset to the definition of a effector gene list.
The new field is set to nullable = True for the time being, so that tests don't complain. This field should be mandatory in the future.

feat(gold_standard): add traitFromSourceMappedId to schema

---

src/gentropy/biosample_index.py
src/gentropy/colocalisation.py
src/gentropy/common/session.py
src/gentropy/config.py
src/gentropy/gene_index.py
src/gentropy/study_locus_validation.py
src/gentropy/study_validation.py
src/gentropy/variant_index.py

As discussed with @javfg the outputs generated by gentropy ETL steps needs to coalesced to minimal number of partitions, so the POS can ingest them without performance issues.
The freeze10 dataset contains following data sizes:
```
7.67 MiB     gs://ot_orchestration/releases/24.11_freeze10/biosample_index/
2.35 GiB     gs://ot_orchestration/releases/24.11_freeze10/colocalisation/coloc/
3.37 GiB     gs://ot_orchestration/releases/24.11_freeze10/colocalisation/ecaviar/
5.72 GiB     gs://ot_orchestration/releases/24.11_freeze10/colocalisation/
2.12 GiB     gs://ot_orchestration/releases/24.11_freeze10/credible_set/
3.03 MiB     gs://ot_orchestration/releases/24.11_freeze10/gene_index/
1.89 GiB     gs://ot_orchestration/releases/24.11_freeze10/invalid_credible_set/
4.01 MiB …
```

feat: coalescing the datasets

---

src/vep/Dockerfile

- The VEP docker file has a fixed VEP tag. This needs to be updated to the most recent release. (currently `113.3`)
```bash
curl -O https://ftp.ensembl.org/pub/release-113/variation/indexed_vep_cache/homo_sapiens_vep_113_GRCh38.tar.gz
tar xzf homo_sapiens_vep_113_GRCh38.tar.gz
cd homo_sapiens/
gsutil -m cp -r 113_GRCh38 gs://genetics_etl_python_playground/vep/cache/homo_sapiens
```
```txt
gs://genetics_etl_python_playground/vep/cache/AlphaMissense_hg38.tsv.gz
gs://genetics_etl_python_playground/vep/cache/AlphaMissense_hg38.tsv.gz.tbi
gs://genetics_etl_python_playground/vep/cache/CADD_GRCh38_whole_genome_SNVs.tsv.gz
gs://genetics_etl_python_playground/vep/cache/CADD_GRCh38_whole_genome_SNVs.tsv.gz.tbi
gs://genetics_etl_python_playground/vep/cache/Homo_sapiens.GRCh38.dna.primary_assembly.fa. …
```

chore(vep): Ensembl version update

---

Makefile

`git rev-parse --abbrev-ref HEAD` command returns `HEAD` when the repository sits in the tag
This PR fixes the issue with `make build` that does not capture the tag and builds the artifacts under incorrect namespace.

feat: allow building package from tag

---

Makefile

As @DSuveges found, there was an issue with how `make build` works. The condition to get the REF was swapped in Makefile, this PR attempts to fix it.
Tested on this branch and tag `test` and this branch build the artifacts with correct namespaces
```
gentropy [szsz-fix-make-build] make build
Updated property [core/project].
Packaging Code and Dependencies for gentropy-0.0.0
Building gentropy (0.0.0)
- Building sdist
- Built gentropy-0.0.0.tar.gz
- Building wheel
- Built gentropy-0.0.0-py3-none-any.whl
Uploading to gs://genetics_etl_python_playground/initialisation/gentropy/szsz-fix-make-build
Copying file://src/gentropy/cli.py [Content-Type=text/x-python]...
/ [1 files][  546.0 B/  546.0 B]
Operation completed over 1 objects/546.0 B.
Copying file://./dist/gentropy-0.0.0-py3-none-any.whl …
```

fix: swap the ref parse

---

src/gentropy/dataset/l2g_prediction.py
src/gentropy/l2g.py

The feature matrix contains all features we have developed for L2G.
However, that doesn't mean that we want to use all of them during training. Right now, this is true for `isProteinCoding`.
- `add_locus_to_gene_features` didn't take into account the list of features used for training. Now it does
- We were filtering out features with nulls, instead of features equal to 0. Now each prediction only include features that have annotation

fix(l2g_predictions): annotate based on list of features + filter out missing annotation

---

.github/workflows/release.yaml

This PR refers to the https://github.com/opentargets/issues/issues/3673.
There were two causes to run twice the downstream jobs on release process was 
Additionally, as we do not use the `release**` branches, I changed the requirement to `publish-to-testpypi` to run on main branch (as a test before the actual pypi release)

fix: release process runs twice

---

.pre-commit-config.yaml

Last merge to dev branch (with swap from poetry to uv) introduced issue with `pycln` package in pre-commit - see [report](https://results.pre-commit.ci/run/github/481607159/1738058313.6CVsocDKQmeRCzB_dTi8rg).
This is well known issue with pycln, that was fixed in latest pycln vesion (2.5.0) - see [issue](https://github.com/hadialqattan/pycln/pull/250)
Bump the version of `pycln` to 2.5.0

chore: bump pycln version

---

.pre-commit-config.yaml
tests/gentropy/dataset/test_colocalisation.py
tests/gentropy/dataset/test_dataset.py
tests/gentropy/dataset/test_l2g.py
tests/gentropy/dataset/test_l2g_feature.py
tests/gentropy/dataset/test_l2g_feature_matrix.py
tests/gentropy/dataset/test_study_locus.py
tests/gentropy/datasource/biosample_ontologies/test_biosample_ontology.py
tests/gentropy/datasource/ensembl/test_vep_variants.py
tests/gentropy/datasource/finngen/test_finngen_study_index.py
tests/gentropy/datasource/gnomad/test_gnomad_ld.py
tests/gentropy/datasource/gwas_catalog/test_gwas_catalog_curation.py
tests/gentropy/datasource/open_targets/test_l2g_gold_standard.py
tests/gentropy/datasource/open_targets/test_variants.py
tests/gentropy/method/test_colocalisation_method.py
tests/gentropy/method/test_locus_breaker_clumping.py
tests/gentropy/method/test_susie_inf.py
tests/gentropy/step/test_colocalisation_step.py
tests/gentropy/step/test_convert_to_vcf_step.py
tests/gentropy/step/test_credible_set_qc.py
tests/gentropy/test_schemas.py
tests/gentropy/test_spark_helpers.py

Last merged PR (https://github.com/opentargets/gentropy/pull/976 ) causes pre-commit checks to fail with error `error: can't find Rust compiler`
Temporarily reverting the changes fix the issue.
https://github.com/opentargets/gentropy/pull/976 introduced a jump in Ruff pre-commit from v0.7.4 to v0.9.3 could have introduced new features or changes that require Rust to be installed, especially since Ruff heavily relies on the Rust toolchain for performance.
I have tried adding the Rust installation inside `install-dependencies.sh` like so:
```sh
if ! command -v rustc &>/dev/null; then
echo "Rust was not found, installing Rust..."
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
source "$HOME/.cargo/env"
echo "Rust installed successfully."
fi
```
but that didn't fix the …

chore: revert pre-commit update (a99ca8490ae6feab2494f9283f49b329d488116b)

---

Makefile

Ensure we track the cost of the local dataproc clusters with labels build from gentropy Makefile.
This PR adds labels to the `make create-dev-cluster` command to ensure we can refer to the costs of the dataproc clusters post mortem.
Added labels:
1. team=open-targets
2. subteam=gentropy
3. created_by=$(USER)
4. environment=development
The format of the label [see docs](https://cloud.google.com/dataproc/docs/guides/creating-managing-labels#requirements)
These labels attempt to follow the standard created for the unified pipeline.

feat: labels for dataproc in dev mode

---

src/gentropy/dataset/variant_index.py

With the latest PR (#947) a bug got introduced into Fold-X energy normalisation. This fix ensures the full free energy range is covered.

fix: foldX normalisation to cover full range

---

src/gentropy/dataset/dataset.py

`Dataset.filter` returns a new instance where the data is filtered based on a given condition.
The new instance didn't keep all attributes the instance may have.
This has been pointed out by @xyg123, who run into an issue when running the L2G predictions step because the model wasn't bound to the predictions instance.
- Fix in `Dataset.filter`

fix(dataset): `filter` maintains instance attributes

---

src/gentropy/l2g.py
src/gentropy/method/l2g/model.py

This PR fixes 2 minor bugs that was causing the L2G prediction step to crash when `model_path=None`:
- `L2GPrediction.from_credible_set` defaults to the `opentargets/locus_to_gene` repo if model_path is none. Now, at the L2G step level this variable matches `hf_repo_id` as long as `download_from_hub` is set to true
- Small typo in the filename of the training set when exporting to HF

fix(l2g): direct model path to hf repo when none and align training data filename

---

src/gentropy/dataset/l2g_prediction.py

L2G prediction step is exceedingly long. We estimate that it runs in ~5h, despite last week we generated predictions with explanations in 30 min.
We believe this is because of 2 main changes:
- L2G model is more than twice as big
- L2G training set that we passed as background dataset is more than twice as big
This slows down the SHAP values estimation.
This PR applies sampling over the training set so that we only pass 1,000 records to the explainer. Based on the latest model and latest training set, we get a **base value of 0.06 with this**, very similar to the previous one. 
This was tested here https://github.com/opentargets/issues/issues/3755#issuecomment-2639518734
To investigate model size.

chore(shap): sample background dataset to make explanation faster

---

src/gentropy/method/colocalisation.py
tests/gentropy/method/test_colocalisation_method.py

Change posterior threshold to 0.1 based on logBF ratio analysis (link).
In the future, this parameter should be exposed to the orchestration config.
- [ x] Do these changes cover one single feature (one change at a time)?
- [ x] Did you read the [contributor guideline](https://opentargets.github.io/gentropy/development/contributing/#contributing-checklist)?
- [ x] Did you make sure to update the documentation with your changes?
- [ x] Did you make sure there is no commented out code in this PR?
- [ x] Did you follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standards in PR title and commit messages?
- [ x] Did you make sure the branch is up-to-date with the `dev` branch?
- [ x] Did you write any new necessary tests?
- [ x] Did you make sure the changes pass …

fix: change posterior filter

---

src/gentropy/config.py
src/gentropy/l2g.py

In order to evaluate the latest model, I want to run the predictions step without extracting SHAPs.
I've tested this works in this [job](https://console.cloud.google.com/dataproc/jobs/e0f30568-52b5-4c09-b285-a087b14855e5/monitoring?region=europe-west1&authuser=1&inv=1&invt=AbrDlg&project=open-targets-genetics-dev).
- Adds `explain_predictions` (set to False by default) as a parameter to the L2G step

chore(l2g): make shap optional

---

src/gentropy/config.py

We have re run another round of hyperparam tuning on this grid of params (2916 total combinations):
```
params = {
'learning_rate': [0.01, 0.1, 0.5],
'subsample': [0.5, 0.7, 1.0],
'max_depth': [3, 5, 7, 10],
'ccp_alpha': [0.0, 0.001, 0.01],
'min_samples_leaf': [1, 5, 10],
'min_samples_split': [2, 5, 10],
'tol': [0.0001, 0.001, 0.01]
}
```
Based on all results, we have selected the **best params that give the best results in terms of average precision.**
```
Performing cross-validation...
Fold 1: Average Precision = 0.826
Fold 2: Average Precision = 0.704
Fold 3: Average Precision = 0.870
Fold 4: Average Precision = 0.691
Fold 5: Average Precision = 0.727
Cross-validation Average Precision: 0.763 (+/- 0.142)
(Config: best) - Training final model on full training set...
(Config: best) - …
```

feat(l2g): update params after fine tuning for the new training data

---

src/gentropy/datasource/gwas_catalog/study_index.py

Previously, when `curation_table` was `None`, the `qualityControls` and `analysisFlags` columns were not being added as intended. This could lead to inconsistencies when handling study data. The fix ensures that these columns are always present, even when no curation table is provided.  
- Ensures that `qualityControls` and `analysisFlags` columns are always added to `studies` before checking for `curation_table`.  
- Returns a new `StudyIndexGWASCatalog` object instead of `self` when `curation_table` is `None`, preserving the modified DataFrame with the added columns.  
Nothing—this PR fully implements the intended fix.

Fix: Ensure `qualityControls` and `analysisFlags` columns are always added when `curation_table` is None

---

src/gentropy/config.py
src/gentropy/l2g.py
src/gentropy/method/l2g/trainer.py
tests/gentropy/conftest.py
tests/gentropy/dataset/test_l2g.py
tests/gentropy/method/test_l2g_trainer.py

Closes https://github.com/opentargets/issues/issues/3440#issue-2507945734
- `wandb_run_name` is now nullable in the L2G Step Config
- Added `LocusToGeneTrainer.evaluate` to extract metrics. This method is now used by several functions, depending whether or not you log to W&B
- Refactor of ` LocusToGeneTrainer.cross_validate` to make it independent of the W&B API
- Added tests for the L2G trainer to make sure the `train` method works on dummy data
- `hf_repo_id` and ` hf_commit_message`  are no longer set by default. This is because when you set these params to null in the orchestration, the null is not interpreted correctly and it was trying to save the model using `https://huggingface.co/api/models/None/preupload/main`
Testing the approach on W&B with cross validation on.

refactor(l2g): make wandb logging optional

---

src/gentropy/dataset/l2g_features/distance.py

I've modeled the solution by looking at this example:
```
+-------------+---------------+---------------+---------------------+
|    variantId|       targetId|distanceFromTss|distanceFromFootprint|
+-------------+---------------+---------------+---------------------+
|16_975464_G_A|ENSG00000103266|        -295054|               292663|
+-------------+---------------+---------------+---------------------+
distance_score_expr = f.lit(500_000) - f.col("distanceFromTss") + f.lit(1)
df = df.withColumn(
"distance_score",
distance_score_expr,
).withColumn(
"distanceSentinelTss",
f.log10(f.col("distance_score")) / f.log10(f.lit(500_000 + 1)),
)
df.show()
+-------------+---------------+---------------+---------------------+--------------+-------------------+
|    variantId| …
```

fix(l2g): half of the feature matrix have distance features larger than 1

---

src/gentropy/dataset/study_index.py

Apparently spark optimisation interferes with the logic in the study validation step. We have to persist datasets to prevent optimisation. For more details, see issue: [#3906](https://github.com/opentargets/issues/issues/3906)

fix: spark plan optimisation

---

src/gentropy/datasource/finngen/study_index.py

Finngen data releases are not tied to publications, therefore so far studies from this source were ingested without pmids. This have some unexpected consequences eg. it is not possible to timestamp disease target evidence based on Finngen credible sets. This PR links all R12 finngen studies with ["36653562"](https://pubmed.ncbi.nlm.nih.gov/36653562/), which is the most recent publication of the Finngen core team. 
Also all hard-coded fields of the study index are extracted to the top of the class definition to make it easier to change in the future.

feat: adding pmid to finngen studies

---

src/gentropy/config.py

Small bug in the configuration. `append_null_features` was added to the L2G step instead of the Feature Matrix Step

fix(l2g): move `append_null_features` param to feature matrix step
