opentargets/gentropy

Makefile
configs/config.yaml
poetry.lock
pyproject.toml
src/intervals/Liftover.py
src/intervals/andersson2014.py
src/intervals/javierre2016.py
src/intervals/jung2019.py
src/intervals/thurman2012.py

Adding parsers to generate intervals dataset.
1. Create bundle: `make build`
2. Create dataproc cluster: `make prepare_intervals`
3. Run script on cluster: `make run_intervals`

feat: Adding parsers for intervals dataset.

---

src/run_intervals.py

Unfortunately the main script, that calls all the parsers for the different interval datasets were missing. I am adding it now. the script was tested and passes all the checks.

The main interval script is added to the repo

---

.gitignore
.pre-commit-config.yaml
.vscode/settings.json
Makefile
README.md
configs/config.yaml
configs/datarelease/dummy.yaml
configs/environment/dataproc.yaml
configs/environment/local.yaml
configs/etl/reference.yaml
configs/machine/dataproc.yaml
poetry.lock
pyproject.toml
src/common/ETLSession.py
src/common/Log4j.py
src/intervals/Liftover.py
src/intervals/andersson2014.py
src/intervals/javierre2016.py
src/intervals/jung2019.py
src/intervals/thurman2012.py
src/run_coloc.py
src/run_intervals.py
utils/configure.py

Changes include:
- Dynamic configs using hydra (see README)
- ETLSession initialises spark session
- Moving to Spark logging instead of python logging
- Missing dependencies added (e.g. mypy, flake8 extensions)
- Missing dependencies added (e.g. pandas)
- Unnecessary logic removed from intervals
- Mypy added to precommit
- VScode workspace settings include lintrs
BREAKING CHANGE: ETLSession class to initialise Spark/logging

feat: modular hydra configs and other enhancements

---

.vscode/settings.json
poetry.lock
pyproject.toml

- iPython is installed as development dependency
- Vscode configured to run with ipython

feat: ipython support

---

docs/modules/variants.md
mkdocs.yml
src/etl/variants/__init__.py
src/etl/variants/variant_annotation.py

the __init__ script was missing!

Adding variant pipeline docs

---

.github/workflows/pytest.yaml
codecov.yml

Aiming to report a coverage target and a tolerance threshold

codecov coverage target

---

.pre-commit-config.yaml
Makefile
utils/install_dependencies.sh

This separates the dependency installation into a separate script and adds the following functionality:
* If necessary, install and configure Pyenv
* If necessary, install Poetry
* Autodetect and, if necessary, install the Python version required for the project
* Activate the appropriate Python version for the project

Amend and separate the script for dependency installation

---

src/otg/method/pics.py
tests/method/test_pics.py

Can we double-check this test? I think it's doing the right thing but I would appreciate another pair of eyes.

test: is in credset function

---

Makefile
README.md
workflow/dag.yaml
workflow/workflow_template.py

Closes https://github.com/opentargets/issues/issues/2946.
* Updated make build to upload code to a version specific path
* Updated workflow_template.py to run the code from that version specific path
* Replaced hardcoded parameters in workflow_template.py with customisable ones
* Amended developer documentation to make it clear how versioning works

Implement version aware code deployment

---

Makefile

New makefile rule to help remote development:
- Builds the project
- Creates a n1-standard-16 Dataproc cluster with the project installed. The name is based on the version
No maximum idle time, instead of sending jobs (which is also possible), my intention is to connect VSCode to the cluster and work remotely.

feat: add create-dev-cluster rule to makefile

---

src/otg/method/window_based_clumping.py

Trying to provide an example on how the structure could look like. Take or discard, this is just for inspiration. No need to merge this. Tests pass but they are not complete.

chore: suggestions on structure

---

docs/assets/stylesheets/extra.css

Solves problem causing avatars in documentation to be stacked instead of inline

fix: stacking avatars in docs

---

src/otg/method/pics.py

- bugfix to close https://github.com/opentargets/issues/issues/3016

fix: avoid empty credible set (#3016)

---

deprecated_tests/test_coloc.py
src/otg/assets/schemas/study_locus.json
src/otg/common/schemas.py
src/otg/dataset/study_locus.py
src/otg/method/clump.py
src/otg/method/pics.py
tests/conftest.py
tests/dataset/test_study_locus.py
tests/method/test_clump.py
tests/method/test_pics.py

Former `credibleSet` is now named `locus`

feat: rename credibleSet to locus

---

src/otg/method/window_based_clumping.py

There were a few minor details in the locus collecting branch of the clumping logic that introduces some problems. Needed to fix

fix: cleaning clumping

---

src/otg/dataset/study_locus.py
tests/dataset/test_study_locus.py

when doing a when/otherwise both schemas had to be the same. Only handling the when solved the problem

fix: schema issues due to when condition

---

src/otg/dataset/summary_statistics.py
tests/method/test_window_based_clumping.py

A trivial update in making window based clumping more intuitive.

Ds 3117 refactor clumping

---

.github/dependabot.yaml
.github/workflows/pytest.yaml

Activates dependabot for poetry/pip and github actions

Github dependabot

---

docs/development/airflow.md
docs/development/contributing.md
src/airflow/dags/common_airflow.py
src/airflow/dags/dag_genetics_etl.py

First part of updates https://github.com/opentargets/issues/issues/3143, split for readability and easier review. This PR only contains style changes.
* Streamlined style and tone of the documentation
* Fixed formatting of the numbered list and code block under "Advanced configuration"
* Updated all variable names in `common_airflow.py` to upper case in line with PEP8
* Fixed numbered list formatting in the contributing checklist (while I'm at it)

Airflow set up, part 1: Style updates for docs and DAG code

---

config/datasets/gcp.yaml
config/step/ld_index.yaml
src/otg/datasource/gnomad/ld.py
src/otg/ld_index.py

We concluded we could benefit from datasources containing default paths for sources are there relatively static and we depend on production-ready datasets.

gnomAD LD datasource with paths within class

---

.pre-commit-config.yaml
src/airflow/dags/common_airflow.py

My apologies, there's a missing field in the chain which slipped through refactors and rebases. I've verified that this now works and the cluster is created without an issue.
Please feel free to merge this PR immediately once approved.

Fix local SSD attachment syntax

---

.gitignore

gitignore env file

---

.github/workflows/release.yaml

This PR removes the --noop option that ensures dry-runs

feat: activate release process

---

pyproject.toml

Problems with the release process

fix: release build using poetry

---

.github/workflows/pr.yaml

It won't fail CI if error with codecov

feat: not fail CI if codecov error

---

.github/workflows/release.yaml

Based on `https://github.com/python-semantic-release/upload-to-gh-release`

fix: release action

---

pyproject.toml

Attempting to populate the respective section from pipy

docs: documentation link

---

README.md
docs/howto/run_step_in_cli.md
docs/index.md
docs/python_api/_python_api.md
docs/python_api/datasources/_datasources.md
docs/python_api/datasources/finngen/summary_stats.md
docs/python_api/steps/colocalisation.md
docs/python_api/steps/eqtl_catalogue.md
docs/python_api/steps/finngen_studies.md
docs/python_api/steps/finngen_sumstat_preprocess.md
docs/python_api/steps/gene_index.md
docs/python_api/steps/gwas_catalog_curation.md
docs/python_api/steps/gwas_catalog_inclusion.md
docs/python_api/steps/gwas_catalog_ingestion.md
docs/python_api/steps/gwas_catalog_sumstat_preprocess.md
docs/python_api/steps/l2g.md
docs/python_api/steps/ld_clump.md
docs/python_api/steps/ld_index.md
docs/python_api/steps/pics.md
docs/python_api/steps/variant_annotation_step.md
docs/python_api/steps/variant_index_step.md
docs/python_api/steps/variant_to_gene_step.md
docs/python_api/steps/window_based_clumping.md

All stylistic and very minor. Finngen summary stats were missing in docs as well

docs: docs ammendments

---

config/datasets/ot_gcp.yaml
config/step/ot_finngen_studies.yaml
src/airflow/.env
src/airflow/dags/finngen_preprocess.py
src/gentropy/config.py

This is a small PR with the updated configuration for finngen. More details on the paths: [#3193](https://github.com/opentargets/issues/issues/3193)

chore: harmonizing finngen configuration

---

.github/dependabot.yaml
.github/workflows/pr.yaml
config/datasets/ot_gcp.yaml
config/step/ot_finngen_studies.yaml
docs/__init__.py
docs/howto/python_api/a_creating_spark_session.md
docs/howto/python_api/b_create_dataset.md
docs/howto/python_api/c_applying_methods.md
docs/howto/python_api/d_inspect_dataset.md
docs/src_snippets/howto/python_api/a_creating_spark_session.py
docs/src_snippets/howto/python_api/b_create_dataset.py
docs/src_snippets/howto/python_api/c_applying_methods.py
docs/src_snippets/howto/python_api/creating_spark_session.py
docs/src_snippets/howto/python_api/d_inspect_dataset.py
mkdocs.yml
poetry.lock
pyproject.toml
src/airflow/dags/finngen_preprocess.py
src/gentropy/config.py
tests/conftest.py
tests/docs/test_applying_methods.py
tests/docs/test_create_dataset.py
tests/docs/test_creating_spark_session.py
tests/docs/test_inspect_dataset.py

This PR goes against `il-howtos` and presents a proof of concept to test the python snippets in the documentation using pytest.

test(docs): testing doc snippets proof of concept

---

src/gentropy/method/carma.py
tests/gentropy/method/test_carma.py

This PR adds time restriction on CARMA using 10 min as a default. If it exceeds the computation time it returns empty list of outliers.

feat(CARMA): adding time limited CARMA

---

src/gentropy/datasource/intervals/thurman.py

As I understand it, the thurman file does not have a header, so header should be set to false when reading the thurman file to include the first line.
Read the first line of the thurman interval dataset.
Depends on https://github.com/opentargets/gentropy/pull/533. I will rebase this branch once that PR is solved.

fix(datasource): read function for thurman data to include first line

---

.github/labeler.yml

PR labeller is not working
https://github.com/opentargets/gentropy/actions/runs/8256074633/job/22583947539
I believe I introduced a bug when changing the pattern in #523
Reverts one line
Not tested

ci: bugfix in PR labeller

---

src/gentropy/susie_finemapper.py

Small fix that adds deduplication of GWAS locus in fine-mapper.
See above.
-

fix: adding deduplication for GWAS in locus

---

src/gentropy/susie_finemapper.py

Adds initialiser to the susie finemapper step.

feat: adding init to finemapping step

---

src/gentropy/config.py
src/gentropy/susie_finemapper.py

fix: update error in config.py

---

src/gentropy/datasource/gnomad/ld.py
src/gentropy/susie_finemapper.py

Updates the locus window parameters to be radii instead of start to end distance.

feat: updating loci windows to locus radii

---

src/gentropy/dataset/study_locus.py
tests/gentropy/dataset/test_study_locus_overlaps.py

Added a bool variable to find_overlaps() and _overlapping_peaks(). By default it is false and has current behaviour. intra_study_overlap = True, it will only find overlaps within the same study and regardless of studyType. 
This will be useful for doing quality control checks on the results of finemapping.

feat: functionality added to StudyLocus.find_overlaps() for finding within-study overlaps

---

.github/workflows/artifact.yml

Trying to hot fix errors in the docker GitHub Action

fix: docker action fixes

---

.github/workflows/artifact.yml

fix: docker action fixes v2

---

src/gentropy/susie_finemapper.py

Checks if the sumstat - LD index join is empty, and if so logs warning and terminates run.

feat: check for if no overlapping variants in LD index

---

.github/workflows/release.yaml

Fix python semantic release version to prevent issues with newer python versions

fix: fix python-semantic-release version

---

docs/roadmap.md

fix(docs): update roadmap.md

---

docs/python_api/datasets/l2g_prediction.md

Missing schema of the `L2GPrediciton` dataset
fix typo in the schema json file name in gentropy docs.

fix(docs): fixed typo in l2g_prediciton schema page

---

config/datasets/ot_gcp.yaml
config/step/ot_locus_to_gene_predict.yaml
src/airflow/dags/finngen_preprocess.py
src/airflow/dags/genetics_etl.py
src/gentropy/common/types.py
src/gentropy/config.py
src/gentropy/dataset/l2g_prediction.py
src/gentropy/l2g.py

The context of the changes can be found in https://github.com/opentargets/issues/issues/3327
Implementations for:
This is second PR for the issue, previous has extracted the p-value threshold value to the config and changed it in the airflow layer.
*Few small changes, that describe single issue.*
*The code in `L2G` and `LocusToGeneStep` is being revisited by @ireneisdoomed, so minimal changes are added here to prevent unnecessary merges.*

feat(data_release): preparation for 24.06 data release

---

src/gentropy/dataset/study_locus.py

Replicated the `exclude_region()` function from `SummaryStatistics` into `StudyLocus`. Additionally, has an option to exclude any StudyLocus where the window, by locusStart and locusEnd, overlaps with the input region.

feat: exclude region for StudyLocus object

---

config/step/ot_finngen_studies.yaml
config/step/ot_finngen_sumstat_preprocess.yaml
config/step/ot_gwas_catalog_sumstat_preprocess.yaml
config/step/ot_pics.yaml
config/step/ot_window_based_clumping.yaml
src/airflow/dags/finngen_harmonisation.py
src/airflow/dags/finngen_preprocess.py
src/airflow/dags/gwas_catalog_harmonisation.py
src/airflow/dags/gwas_catalog_preprocess.py
src/gentropy/config.py

This is the beginning of a series of work intended to move the airflow layer outside the gentropy package. 
This is a refactor to remove step configurations that were unnecessary because they were configured entirely in the Airflow layer.

refactor: delete unnecessary config files

---

.pre-commit-config.yaml

Attempt to resolve isssue with dev branch. If this solves the issue we might need to find out why is failing

fix: remove check merge conflict from pre-commit

---

src/gentropy/config.py
src/gentropy/sumstat_qc_step.py

feat: add qc step

---

src/gentropy/gwas_catalog_sumstat_preprocess.py

feat: adding sanity filter to GWASCatalogSumstatsPreprocessStep

---

src/gentropy/config.py
src/gentropy/credible_set_qc.py
src/gentropy/dataset/summary_statistics.py
src/gentropy/method/susie_inf.py
src/gentropy/susie_finemapper.py

feat: credible set quality control step

---

Dockerfile

This PR adds two new dependencies to the gentropy docker container:
Both dependencies are required for running the google batch scripts that will wrap over the gentropy. jq is used to the parse the manifest json blob and save manifest to google storage from bash script.

feat(docker): image update for new orchestration

---

.github/workflows/artifact.yml

Added tags to the `artifact.yaml` github actions triggers.
in case of a tag, the version of the image will reflect the tag name (by `github.ref_name`)

ci: artifacts versionned by release

---

.github/workflows/release.yaml

The `python-semantic-release` v9.8.3 uses python 3.12 that causes poetry to fail during the release build process.
Offending action result in the [link](https://github.com/opentargets/gentropy/actions/runs/9908916068/job/27377227141)
@tskir FYI

ci: revert semantic-release update

---

.github/workflows/artifact.yml
.github/workflows/release.yaml
Dockerfile

The context for the PR can be found in https://github.com/opentargets/issues/issues/3384
these changes can be tested during next relase only

ci: Refactoring of the docker release process for gentropy

---

.github/workflows/artifact.yml

Continuation of #700, the docker images are build correctly with new action on dev branch - see https://github.com/opentargets/gentropy/actions/runs/9955215465/job/27502478363, now we can push them to the registry.

feat: allow image push

---

config/step/ot_gwas_catalog_ingestion.yaml
config/step/ot_gwas_catalog_study_inclusion.yaml

Some parameter names were not changed with the update #641 https://github.com/opentargets/gentropy/commit/f79c789ae2ef0fa8f55e9ca2a78088db9dd14512.
This PR attempts to resolve them.

fix: change config params to match new name

---

Makefile

This PR updates the Make command for creating dataproc cluster. The cluster is bound to the user and created with maximum idle time of 30 minutes before decomissioned.

fix: update cluster creation command

---

src/gentropy/common/session.py

After https://github.com/opentargets/gentropy/pull/735 the `VariantIndexStep` produces the `VariantIndex` table that is [partitionned by chromosome](https://github.com/opentargets/gentropy/blob/dc8c9dc63376bdc353771d7158060494a8a62434/src/gentropy/variant_index.py#L62) (previously the dataframe was collected by pandas and saved without partitionning).
To preserve the partitioning column, we need to drop the recursiveFileLookup when reading variant index in `LocusToGeneStep`, otherwise the `chromosome` column is Null.

fix: VariantIndex partitioned by chromosome has to be read without resursive file lookup flag

---

src/gentropy/datasource/finngen/study_index.py

Preserve all studyIds in the Finngen StudyIndex, even if EFO mapping is missing, so mapping between studyIndex and StudyLocus is by studyId column is accurate. This is to avoid discrepancies between `study_index` an`credible_set` `studyId` column. The rows with missing EFO mappings will be dropped in the study_index validation step.

fix(finngen_r11): preserve all studyIds

---

src/gentropy/assets/schemas/study_index.json
src/gentropy/datasource/eqtl_catalogue/finemapping.py

The `condition` of the eQTL studies (e.g., IFNg_18h+Salmonella_5h) is currently used to build the identifier, but it's not part of a separate column that could populate the FE.
`condition` is added to the eQTL study index and the corresponding schema

feat: add condition to eQTL study index and schema

---

src/gentropy/dataset/study_locus.py
src/gentropy/study_locus_validation.py
tests/gentropy/dataset/test_study_locus.py

Closes https://github.com/opentargets/issues/issues/3508

feat: flag PICS top hits in studies with PICS from sumstats

---

src/gentropy/dataset/study_index.py
src/gentropy/study_locus_validation.py
src/gentropy/study_validation.py

Small QC flag fixes in study_vlaidation and study_locus_validation

fix: small qc flag fixes

---

notebooks/README.md
notebooks/Release_QC_metrics.ipynb
src/gentropy/datasource/ukb_ppp_eur/study_index.py

Change the name `tissueFromSourceId` to `biosampleFromSourceId` to match the schema.

fix: align the schema of study_index for ukb ppp eur

---

utils/install_dependencies_on_cluster.sh

Allow for reinstallation of the gentropy without caching the package version. 
This allows for `install_dependencies` usage in the orchestration

feat: force reinstallation of the gentropy on the cluster

---

src/gentropy/locus_breaker_clumping.py

Allow to read partitionned sumstat files. This will not break how the gwas catalog sumstat will be read. 
- [ x Did you make sure the changes pass pre-commit rules (e.g `poetry run pre-commit run --all-files`)?

chore: make the lb clumping ingest the partitionned data

---

src/gentropy/assets/schemas/study_index.json

https://github.com/opentargets/issues/issues/3557

feat: add sumstat QC fields to schema

---

src/gentropy/method/locus_breaker_clumping.py

fix: fix of type error in schema checking

---

src/gentropy/susie_finemapper.py

fix: adding studId to FM log

---

src/gentropy/dataset/study_locus.py

Incorrect flagging of MHC region

fix: mhc flag incorrect

---

.github/workflows/pr.yaml

Github Actions has updated the Java version to Java 17, causing several tests that involve Hail to fail.
This PR adds an action that installs Java version 8, which is compatible with the Gentropy dependencies, and is the same one used in Dataproc.
More details: https://github.com/marketplace/actions/setup-java-jdk

ci: configure java v8

---

src/gentropy/dataset/l2g_feature_matrix.py
src/gentropy/l2g.py

feat(l2g): persist feature matrix in l2g training plan

---

src/gentropy/datasource/ukb_ppp_eur/study_index.py
src/gentropy/ukb_ppp_eur_sumstat_preprocess.py

fix: fix ukbppp studindex

---

poetry.lock
src/gentropy/config.py
src/gentropy/dataset/l2g_feature_matrix.py
src/gentropy/dataset/l2g_gold_standard.py
src/gentropy/dataset/study_locus_overlap.py
src/gentropy/l2g.py
tests/gentropy/conftest.py
tests/gentropy/dataset/test_l2g.py
tests/gentropy/dataset/test_l2g_feature_matrix.py
tests/gentropy/dataset/test_study_locus_overlap.py

Multiple minor iterations to get L2G running containing several small fixes.

fix: l2g fixes

---

src/gentropy/susie_finemapper.py

Updating the init function for susie_finemapper step to use LDMatrixInterface.

fix: updating the susie_finemapper init

---

src/gentropy/susie_finemapper.py

fix: filter nan in CSs

---

src/gentropy/susie_finemapper.py

fix: adding beta for lead variant

---

src/gentropy/susie_finemapper.py

fix: logging of finemamper

---

src/gentropy/dataset/dataset.py
src/gentropy/dataset/variant_index.py
src/gentropy/datasource/ensembl/vep_parser.py
src/gentropy/variant_index.py
tests/gentropy/dataset/test_dataset.py
tests/gentropy/dataset/test_variant_index.py
tests/gentropy/datasource/ensembl/test_vep_variants.py

There was a problem in the variant index step that caused all IDs above the default threshold of 100 to be hashed, even though this threshold was set to 300 in the configuration.
```
variant_index.df.withColumn(
"variantId",
VariantIndex.hash_long_variant_ids(
col("variantId"), col("chromosome"), col("position")
),
)
```
This was because this step: a) created a Variant Index from VEP, that was hashed, b) read the Gnomad variant index, not hashed, c) joined both of them and then hashed again but without passing the parameter.
There are **2 issues** in this process:
1. Gnomad Variant index wasn't hashed, so that for variants longer than 300, the join with the VEP output wasn't successful
2. We forgot to pass the threshold in step number 3, so we hashed everything longer than 100
- To avoid …

feat(variant_index): hash variants at the time of instance creation

---

src/gentropy/dataset/study_locus.py

Fix in calculate_credible_set_log10bf function: it should return log10, not log

fix: fix in calculate_credible_set_log10bf

---

docs/python_api/datasets/l2g_features/other.md
src/gentropy/config.py
src/gentropy/dataset/l2g_features/other.py
src/gentropy/method/l2g/feature_factory.py
tests/gentropy/dataset/test_l2g_feature.py

This PR closes https://github.com/opentargets/issues/issues/3588
New feature following this scoring:
```
FINEMAPPED_IN_SAMPLE_LD: 1
FINEMAPPED_IN_SAMPLE_LD: 0.75
PICSED_SUMMARY_STATS: 0.5
PICSED_SUMMARY_STATS: 0.25
UNKNOWN: 0
```

feat(l2g_feature_matrix): add `credibleSetConfidence` to L2G

---

src/gentropy/config.py
src/gentropy/l2g.py

Context in https://github.com/opentargets/issues/issues/3612#event-15183942505
PR to the orchestration repo: https://github.com/opentargets/orchestration/pull/74

chore(l2g): parametrise score threshold when writing predictions

---

src/gentropy/study_locus_validation.py

Turning on chromosome validation for study loci.

chore: validate chromosome

---

src/gentropy/common/utils.py

Due to the possibility of multiple alt contigs in `variantId` field, we want to be able to parse them correctly.

feat: extract pos and chromosome from variantid

---

src/gentropy/dataset/study_locus.py
src/gentropy/datasource/gwas_catalog/study_index.py
src/gentropy/method/pics.py
tests/gentropy/dataset/test_study_locus.py

PICS credible sets are missing the `OUT_OF_SAMPLE_LD` QC flag.
`pics` should be named `PICS` as it is an acronym.
This PR adds the `OUT_OF_SAMPLE_LD` QC flag to PICS credible sets, and renames `pics` to `PICS`.
When running the `gwas_catalog_top_hits` DAG, the initial implementation of the `add_no_sumstats_flag` function did not work as it relied on the existence of the `hasSumstats` and `qualityControls` columns. The function has now been simplified to address these issues. (These fixes assume the `add_no_sumstats_flag` function is only used in `GWASCatalogTopHitIngestionStep`)

feat: changes to PICS credible sets (OUT_OF_SAMPLE_LD QC flag and capital PICS)

---

src/gentropy/dataset/study_locus.py
src/gentropy/method/ld.py
src/gentropy/method/pics.py
tests/gentropy/method/test_pics.py

Related to bug when credible set size is zero for 10445 CSs.
The problem is that r2 for the lead variant is 0 for 100% cases.
There are two possible fixes:
1. Ensure that r2 for lead is always 1 in the ld annotation step. 
2. Add the flag "[LD block contains no variants at the required R^2 threshold]" as an exclusion criterion.
This PR fixes 1). Good way to go, but requires recalculation of PICS credible sets.

fix: r2 for lead variant is always 1

---

.github/workflows/artifact.yml

@javfg has raised a request to change the docker tag to skip the leading `v`, this will result in the docker tags `2.1.0` instead of `v2.1.0`. Skipping the leading `v` is not a common thing that can be seen on dockerhub, although I could not find any supporting information for this standard apart from the fact that some users encourage the usage of [semvar](https://semver.org/).
>[!NOTE]
> This change should be followed with the update in the orchestration configuration.
Drop the leading `v` from the docker tag for:
- gentropy image
- custom_ensembl_vep image
the `vX.Y,Z` persists on the software tags (as this explicitly indicates that the tag represents a version.)

fix: skip leading 'v' in docker tag

---

Makefile
docs/development/troubleshooting.md
utils/clean_status.sh

This update to the local dataproc cluster setting allows to tweak the:
- max time the cluster can be used for the interactive jobs only
- ref name (branch) to use when setting up the local cluster - the change allows to use arbitrary ref that exists on the remote origin rather then only the local branch.
Full documentation added to the docs that describe how to build the local cluster.
- add `REF` flag for `make create-dev-cluster REF=dev` to specify the ref to build the cluster with
- add `CLUSTER_TIMEOUT` flag for the `make create-dev-cluster CLUSTER_TIMEOUT=1d` to specify the time cluster can run without job submittion.

feat: local dataproc cluster settings udpate

---

src/gentropy/datasource/open_targets/foldex_integration.py

Fixing column name discrepancy in the fold-x dataset ingestion process

fix: foldx column name fix

---

src/gentropy/config.py
src/gentropy/dataset/l2g_prediction.py
src/gentropy/l2g.py
src/gentropy/method/l2g/model.py

Changes in the API that allow to load a specific model by referencing a commit.
This is necessary as we are going to use the `locus_to_gene` repo to store models for several releases.
This is how you can instantiate the model from the December release:
```python
2412_commit = "66657530b74d25b0639740d014d85b8dbe94efc5"
l2g_model = LocusToGeneModel.load_from_hub(
session, "opentargets/locus_to_gene", hf_token, hf_model_version=2412_commit
)
```
- API changes in `load_from_hub` to reference specific commit
- API changes in `L2GPrediction` that calls load from hub
- New parameter in the L2G step to allow instantiation of a particular model
I'd like to create tags to clearly reference the model for each release. It's annoying that you can't easily do this from the UI.
You can use their API or …

feat(l2g): download specific model version from hub

---

src/gentropy/dataset/variant_index.py
src/gentropy/datasource/ensembl/vep_parser.py
src/gentropy/foldx_ingestion.py

- [#3800](https://github.com/opentargets/issues/issues/3800) - fixing typo in variant description
- [#3799](https://github.com/opentargets/issues/issues/3799) - Changing conservation score normalisaion

fix: addressing #3800 and #3799

---

.pre-commit-config.yaml

Ensure the `uv lock` pre-commit action check if the `uv.lock` file is aligned with the `pyproject.toml` list of dependencies. This PR is based on the fact, that we are facing the errors when attempting to run the mentioned pre-commit action on pre-commit ci. 
The change is based on issue posted in https://github.com/astral-sh/uv/issues/10176.
Addition of two flags to the `uv-lock` pre-commit action
`--offline` - Disable network access (prevent the lookup that causes current action fails) see [docs](https://docs.astral.sh/uv/reference/cli/#uv-lock--offline)
`--check` - Check if the lockfile is up-to-date. - see [docs](https://docs.astral.sh/uv/reference/cli/#uv-lock--check)
Although the `pre-commit.ci` does not fail here (I am not sure if these changes are sufficient to fix it on the dev …

chore: offline check uv lock

---

.pre-commit-config.yaml

Follow up on https://github.com/opentargets/gentropy/pull/1024
Due to the fact that the pre-commit ci hosts does not allow for runtime internet access, we can not use the `uv-lock` pre-commit hook while running on the CI. Solution proposed by https://github.com/opentargets/gentropy/pull/1024 (using `--offline` would be good in case we have all expected packages cached on the machine, which is not the case - see [error](https://results.pre-commit.ci/run/github/481607159/1742465019.l0Dpmcj9SH2FFIp_ewZd2Q))

chore: skip uv-lock on pre-commit ci

---

src/gentropy/dataset/colocalisation.py
src/gentropy/dataset/l2g_features/colocalisation.py
src/gentropy/l2g.py
tests/gentropy/dataset/test_colocalisation.py
tests/gentropy/dataset/test_l2g_feature.py
tests/gentropy/dataset/test_l2g_feature_matrix.py

This PR is another version of the changes introduced in https://github.com/opentargets/gentropy/pull/1038, which is that we use colocalisation results from trans QTLs to annotate credible sets for L2G.
Instead of filtering the colocalisation dataset in the feature matrix generation, we make sure that this filter is applied when computing the Colocalisation features. This means that filtering the colocalisation results to only get cis effects is a responsibility of the feature computation, not the step that calls all features.
The function is also tested semantically.
- New method for the Colocalisation dataset: `Colocalisation.drop_trans_effects`
- Semantic test to make sure the filter is applied accordingly
- Usage of this function inside the common logic that computes all colocalisation …

fix: remove trans molQTLs from FM

---

src/gentropy/colocalisation.py
tests/gentropy/step/test_colocalisation_step.py

The `colocalisationStep` appends the colocalisation name to the end of the path where the output is generated effectively transforming `output_path="colocalisation", method_name="coloc"` to `output_path="colocalisation/coloc", method_name="coloc"` 
This PR attempts to remove the behaviour described above, effectively passing the provided parameter directly to the `DataFrameWritter`.

fix: ensure the coloc method name is not added to the output

---

src/gentropy/l2g.py

There were multiple issues reported where FM does not correctly specify certain features due to problems with the conversion from long format to wide format, as we discussed earlier.
However, I have verified the actual correspondence between the isProteinCoding feature and the information from target_index.
There was an 11% discrepancy — that’s 3,608,404 gene-studyLocusId pairs.
This PR is just a simple patch for that. But we need to revise the logic in the future, as the same issue affects distance-based features and similar ones.

fix: fix isProteincoding

---

.vscode/settings.json
src/gentropy/common/harmonise.py
src/gentropy/common/utils.py
src/gentropy/datasource/gwas_catalog/summary_statistics.py
src/gentropy/gwas_catalog_study_index.py
src/gentropy/sumstat_qc_step.py
tests/gentropy/data_samples/empty_stderr_GCST01.h.tsv
tests/gentropy/datasource/gwas_catalog/test_gwas_catalog_summary_statistics.py

Number of MVP studies after harmonisation have empty summary statistics, which is due to the empty `standardError` field. The records with empty `standardError` are dropped in the `sanity_filter` step of harmonisation.
Since we can recalculate the standardError when both `beta` and `p-value` are provided we want to make sure it is there and we do not drop the records. This PR attempts to add a functionality to coalesce nullable `standardError` into calculated one.
The implementation is based on the formula
$zScore = beta / stdError$

feat(sumstat): rescue standard error from p-value and beta 

---

src/gentropy/dataset/l2g_prediction.py
src/gentropy/l2g.py
tests/gentropy/dataset/test_l2g.py

Addressing [#3936](https://github.com/opentargets/issues/issues/3936): 
- Carrying over pubmed identifier from the study index to evidence
- Adding some tests to cover evidence generation.

chore: adding pubmed identifier to evidence
